#  Copyright (C) 2026  EmGi

# You are free to modify it under the terms of the GNU General Public License as published by the Free Software Foundation.
# You are free to use any models Generated by this Addon Commercially

"""Global OSMData water-polygon dataset: download, cache, and spatial query.

Fallback ocean/coastline source for maps too big for the Overpass coastline-way
pipeline (utils/terrain.py::createOcean). Source dataset:

    https://osmdata.openstreetmap.de/data/water-polygons.html
    simplified-water-polygons-split-3857.zip  (ODbL -- derived from OpenStreetMap)

CRS note: this dataset is real EPSG:3857 (WGS84 sphere, radius 6378137 m).
TP3D's own internal Mercator (utils/osm/gen.py::_ll_to_bl and the equivalent
closure in utils/terrain.py::createOcean) uses R = 6371.0 km (constants.R) --
a different sphere. Rather than try to reconcile the two projections, this
module stays entirely in real EPSG:3857 internally and hands back plain
lat/lon, so the caller can re-project through TP3D's own existing formula
exactly like every other OSM-derived element. Do not intersect this dataset's
coordinates directly against TP3D local-space coordinates -- they are not the
same projection.
"""

import math
import os
import zipfile

import requests

from ... import constants as const

OSMDATA_ZIP_URL = (
    "https://osmdata.openstreetmap.de/download/simplified-water-polygons-split-3857.zip"
)

# WGS84 semi-major axis, in meters -- the sphere radius EPSG:3857 is defined
# against. NOT the same as constants.R (6371.0 km), which is a different mean
# earth radius TP3D uses for its own internal Mercator.
_EPSG3857_RADIUS_M = 6378137.0
_EPSG3857_WORLD_EXTENT_M = math.pi * _EPSG3857_RADIUS_M  # ~20037508.34

_ZIP_FILENAME = "simplified-water-polygons-split-3857.zip"
_WKB_FILENAME = "simplified-water-polygons-split-3857.wkb"

# Lazy, in-memory, per-session cache: (list_of_polygons, STRtree). Rebuilding
# the tree only costs ~0.1s per the findings benchmark, but there's no reason
# to pay that more than once per Blender session.
_WATER_INDEX = None


def _zip_path():
    return os.path.join(const.water_cache_dir, _ZIP_FILENAME)


def _wkb_path():
    return os.path.join(const.water_cache_dir, _WKB_FILENAME)


def is_dataset_ready():
    """True if the converted WKB is already cached on disk."""
    return os.path.isfile(_wkb_path())


def download_dataset(progress_cb=None, max_retries=3, timeout=60):
    """Download the OSMData water-polygon zip to the water cache dir.

    progress_cb, if given, is called as progress_cb(fraction, message) with
    fraction in [0, 1] (fraction is None if the server didn't send a
    Content-Length header). Returns True on success, False on failure --
    mirrors the bool-return / retry-loop convention used by
    osm/fetch_utils.py's Overpass requests and satellite.py's tile downloads.
    """
    os.makedirs(const.water_cache_dir, exist_ok=True)
    dest = _zip_path()
    tmp_dest = dest + ".part"

    for attempt in range(max_retries):
        try:
            with requests.get(
                OSMDATA_ZIP_URL,
                stream=True,
                timeout=timeout,
                headers={"User-Agent": "TrailPrint3D_3.00"},
            ) as response:
                if response.status_code != 200:
                    print(
                        f"[TrailPrint3D] water polygon download: status "
                        f"{response.status_code}, retrying... "
                        f"({attempt + 1}/{max_retries})"
                    )
                    continue

                total = response.headers.get("Content-Length")
                total = int(total) if total is not None else None
                downloaded = 0

                with open(tmp_dest, "wb") as f:
                    for chunk in response.iter_content(chunk_size=1024 * 256):
                        if not chunk:
                            continue
                        f.write(chunk)
                        downloaded += len(chunk)
                        if progress_cb:
                            frac = (downloaded / total) if total else None
                            progress_cb(
                                frac,
                                f"Downloading water polygon dataset "
                                f"({downloaded // 1024} KB)",
                            )

            os.replace(tmp_dest, dest)
            return True

        except requests.exceptions.Timeout:
            print(
                f"[TrailPrint3D] water polygon download timed out "
                f"(attempt {attempt + 1}/{max_retries})"
            )
        except requests.RequestException as e:
            print(f"[TrailPrint3D] water polygon download failed: {e}")
        finally:
            if os.path.exists(tmp_dest) and not os.path.exists(dest):
                try:
                    os.remove(tmp_dest)
                except OSError:
                    pass

    print("[TrailPrint3D] water polygon download failed after retries")
    return False


def _convert_zip_to_wkb(zip_path, wkb_path):
    """Extract the shapefile, validate each polygon individually, and write a
    single GeometryCollection WKB -- the "GEOMETRYCOLLECTION EXPERIMENT" /
    "STRtree SOLUTION" result from the findings doc.

    Deliberately does NOT union_all() the ~14k global polygons (that's the
    "noticeably slow" global-union path the findings doc measured and
    rejected). Deliberately does NOT build a bare MultiPolygon either --
    the dataset's split/overlapping world-edge pieces make that invalid.
    """
    import shapefile  # type: ignore -- pyshp - pure Python, bundled as a wheel
    import shapely as _shp

    # import since it's only needed for this one-time conversion step.
    from shapely.geometry import GeometryCollection, shape
    from shapely.geometry.base import BaseGeometry

    extract_dir = wkb_path + ".extract"
    os.makedirs(extract_dir, exist_ok=True)
    try:
        with zipfile.ZipFile(zip_path) as zf:
            zf.extractall(extract_dir)

        shp_path = None
        for root, _dirs, files in os.walk(extract_dir):
            for name in files:
                if name.lower().endswith(".shp"):
                    shp_path = os.path.join(root, name)
                    break
            if shp_path:
                break
        if shp_path is None:
            raise FileNotFoundError(
                "No .shp file found inside the downloaded water-polygon zip"
            )

        polygons = []
        invalid_count = 0
        with shapefile.Reader(shp_path) as reader:
            for sr in reader.shapeRecords():
                geom = shape(sr.shape.__geo_interface__)
                if not isinstance(geom, BaseGeometry) or geom.is_empty:
                    continue
                if not geom.is_valid:
                    invalid_count += 1
                    geom = geom.buffer(0)
                    if geom.is_empty:
                        continue
                polygons.append(geom)

        if invalid_count:
            print(
                f"[TrailPrint3D] water polygon conversion: repaired "
                f"{invalid_count} invalid source polygon(s) via buffer(0)"
            )
        if not polygons:
            raise ValueError("Water polygon shapefile contained no usable polygons")

        collection = GeometryCollection(polygons)
        wkb_bytes = _shp.to_wkb(collection)

        tmp_wkb = wkb_path + ".part"
        with open(tmp_wkb, "wb") as f:
            f.write(wkb_bytes)
        os.replace(tmp_wkb, wkb_path)

    finally:
        # Only the WKB is worth keeping on disk long-term (per the findings
        # doc: "the important runtime artifact is the WKB") -- clean up the
        # much larger zip + extracted shapefile.
        import shutil

        shutil.rmtree(extract_dir, ignore_errors=True)
        if os.path.exists(zip_path):
            try:
                os.remove(zip_path)
            except OSError:
                pass


def ensure_water_dataset(progress_cb=None):
    """Make sure the converted WKB exists on disk, downloading + converting
    if necessary. Returns True if the dataset is ready to query, False on
    failure (caller should warn and skip the water-polygon fallback, same as
    the existing "no coastline data" warning path)."""
    if is_dataset_ready():
        return True

    if not os.path.isfile(_zip_path()) and not download_dataset(
        progress_cb=progress_cb
    ):
        return False

    try:
        if progress_cb:
            progress_cb(None, "Converting water polygon dataset…")
        _convert_zip_to_wkb(_zip_path(), _wkb_path())
    except Exception as e:  # noqa: BLE001 -- surface any conversion failure as a clean False
        print(f"[TrailPrint3D] water polygon conversion failed: {e}")
        return False

    return is_dataset_ready()


def _load_water_index():
    """Lazy-load + cache the (polygons, STRtree) pair for this session."""
    global _WATER_INDEX
    if _WATER_INDEX is not None:
        return _WATER_INDEX

    import shapely as _shp
    from shapely.geometry import GeometryCollection
    from shapely.strtree import STRtree

    with open(_wkb_path(), "rb") as f:
        wkb_bytes = f.read()
    collection = _shp.from_wkb(wkb_bytes)
    if isinstance(collection, GeometryCollection):
        polygons = list(collection.geoms)
    else:
        # Single-polygon dataset edge case -- keep the index shape consistent.
        polygons = [collection]

    tree = STRtree(polygons)
    _WATER_INDEX = (polygons, tree)
    return _WATER_INDEX


def reset_water_index_cache():
    """Drop the in-memory (polygons, STRtree) cache. Mainly for tests / after
    a manual re-download of the dataset."""
    global _WATER_INDEX
    _WATER_INDEX = None


def _forward_3857(lat, lon):
    x = _EPSG3857_RADIUS_M * math.radians(lon)
    y = _EPSG3857_RADIUS_M * math.log(math.tan(math.pi / 4.0 + math.radians(lat) / 2.0))
    return (x, y)


def _inverse_3857(x, y):
    lon = math.degrees(x / _EPSG3857_RADIUS_M)
    lat = math.degrees(
        2.0 * math.atan(math.exp(y / _EPSG3857_RADIUS_M)) - math.pi / 2.0
    )
    return (lat, lon)


def query_ocean_polygon(min_lat, min_lon, max_lat, max_lon, scaleHor):
    """Return the ocean/water Shapely (Multi)Polygon for the requested
    geographic bbox, already reprojected into TP3D's own local Blender-space
    Mercator.

    Longitude is treated as continuous rather than clamped to [-180, 180].
    Requests crossing or extending beyond the antimeridian are split into
    real EPSG:3857 world-space queries. Geometry from wrapped world copies is
    shifted by whole-world widths before merging so the result remains in the
    same continuous longitude space as the requested bbox.

    For example:

        min_lon=179, max_lon=181

    is queried as:

        [179, 180] and [-180, -179]

    with the second result shifted +1 world width so it occupies:

        [179, 181]

    before being converted into TP3D's own Mercator coordinates.
    """
    if not ensure_water_dataset():
        return None

    polygons, tree = _load_water_index()

    from shapely.geometry import box as _box
    from shapely.ops import transform as _shp_transform

    # EPSG:3857 spans exactly one world from -WORLD_EXTENT to +WORLD_EXTENT.
    world_width = 2.0 * _EPSG3857_WORLD_EXTENT_M

    # ------------------------------------------------------------------
    # Build one or more query bboxes representing the requested longitude
    # range, wrapping through the real EPSG:3857 world as necessary.
    #
    # Each entry is:
    #
    #     (bbox_3857, x_offset)
    #
    # x_offset moves geometry from that world copy back into the continuous
    # longitude space of the original request.
    # ------------------------------------------------------------------

    # Keep the caller's longitude space intact. This matters because TP3D's
    # own _ll_to_bl() treats longitude as continuous, so 181 degrees is
    # intentionally to the east of 180 rather than becoming -179.
    request_min_lon = min_lon
    request_max_lon = max_lon

    # Defensive normalization for callers that happen to provide reversed
    # longitude bounds.
    if request_max_lon < request_min_lon:
        request_min_lon, request_max_lon = (
            request_max_lon,
            request_min_lon,
        )

    # Latitude is not periodic. Clamp to Web Mercator's practical limits so
    # _forward_3857() cannot hit log(tan()) singularities at the poles.
    mercator_max_lat = 85.0511287798066
    query_min_lat = max(min(min_lat, max_lat), -mercator_max_lat)
    query_max_lat = min(max(min_lat, max_lat), mercator_max_lat)

    if query_min_lat >= query_max_lat:
        return None

    # Convert the requested continuous longitude interval into overlapping
    # copies of the canonical [-180, 180] EPSG:3857 world.
    #
    # Example:
    #
    #   179 -> 181
    #
    # becomes:
    #
    #   canonical [179, 180], offset 0
    #   canonical [-180, -179], offset +WORLD_WIDTH
    #
    # The result geometry is shifted back into the original continuous
    # longitude space before unioning.
    query_parts = []

    start_world = math.floor((request_min_lon + 180.0) / 360.0)
    end_world = math.floor((request_max_lon + 180.0) / 360.0)

    # Avoid treating an exact world boundary as belonging exclusively to the
    # next copy. A tiny epsilon only affects world-index selection, not the
    # actual geometry coordinates.
    if request_max_lon > request_min_lon:
        end_world = math.floor(((request_max_lon + 180.0) - 1e-12) / 360.0)

    for world_index in range(start_world, end_world + 1):
        world_lon_min = -180.0 + world_index * 360.0
        world_lon_max = 180.0 + world_index * 360.0

        part_min_lon = max(request_min_lon, world_lon_min)
        part_max_lon = min(request_max_lon, world_lon_max)

        if part_max_lon < part_min_lon:
            continue

        # Convert this continuous-world longitude range back into canonical
        # [-180, 180] longitude for querying the actual dataset.
        canonical_min_lon = part_min_lon - world_index * 360.0
        canonical_max_lon = part_max_lon - world_index * 360.0

        sw = _forward_3857(query_min_lat, canonical_min_lon)
        ne = _forward_3857(query_max_lat, canonical_max_lon)

        bbox_3857 = _box(
            min(sw[0], ne[0]),
            min(sw[1], ne[1]),
            max(sw[0], ne[0]),
            max(sw[1], ne[1]),
        )

        query_parts.append(
            (
                bbox_3857,
                world_index * world_width,
            )
        )

    if not query_parts:
        return None

    # ------------------------------------------------------------------
    # Query the STRtree and clip every candidate to its wrapped bbox.
    # Geometry from wrapped copies is translated back into the requested
    # continuous world before merging.
    # ------------------------------------------------------------------

    clipped = []

    for bbox_3857, x_offset in query_parts:
        candidate_idx = tree.query(bbox_3857)

        for i in candidate_idx:
            part = polygons[int(i)].intersection(bbox_3857)

            if part.is_empty:
                continue

            if x_offset != 0.0:
                # Avoid importing affinity just for this tiny translation and
                # keep all operations inside Shapely's coordinate pipeline.
                def _shift_x(x, y, z=None, _offset=x_offset):
                    if z is None:
                        return (x + _offset, y)
                    return (x + _offset, y, z)

                part = _shp_transform(_shift_x, part)

            if not part.is_empty:
                clipped.append(part)

    if not clipped:
        return None

    from .. import geometry2d as _g2d

    merged = _g2d.union(clipped)
    merged = _g2d.validate(merged)

    if merged is None or merged.is_empty:
        return None

    # ------------------------------------------------------------------
    # Convert from real EPSG:3857 into TP3D's own Mercator implementation.
    #
    # Important: the wrapped X coordinates may legitimately fall outside the
    # normal +/- EPSG:3857 world extent. Convert X directly to continuous
    # longitude rather than normalizing it back into [-180, 180].
    # ------------------------------------------------------------------

    def _to_latlon(x, y):
        lat, lon = _inverse_3857(x, y)
        return (lon, lat)

    def _latlon_to_tp3d_local(lon, lat):
        # Mirrors the existing _ll_to_bl closures in osm/gen.py and
        # terrain.py exactly. Longitude is intentionally NOT normalized:
        # lon=181 should remain east of lon=180, matching the caller's bbox.
        x = const.R * math.radians(lon) * scaleHor
        y = (
            const.R
            * math.log(math.tan(math.pi / 4.0 + math.radians(lat) / 2.0))
            * scaleHor
        )
        return (x, y)

    latlon_geom = _shp_transform(_to_latlon, merged)
    local_geom = _shp_transform(
        _latlon_to_tp3d_local,
        latlon_geom,
    )

    return local_geom
