#  Copyright (C) 2026  EmGi

# You are free to modify it under the terms of the GNU General Public License as published by the Free Software Foundation.
# You are free to use any models Generated by this Addon Commercially


'''
Changelog

Version 3.08
 
- Changed: Roads and buildings are no longer clipping into the Map
- Changed: Improved reliability of the Single-color-mode
- Removed: Rescale Elevation (Conflicting with Single-color-mode, Unnecessary since caching)
- Removed: Extrude Terrain (Conflicting with Single-color-mode, Unnecessary since caching)

Version 3.05

- Fixed missing duration for text shapes {duration}
- Fixed crash when using 2 identical icons for text shapes


Version 3.04

- Added Greenspace element (Parks, grass, gardens inside cities)
- Added Another Single-color-mode Algorithm for elements
- Improved existing SCM algorithm for elements. Bevel is now gone and vertice count reduced massively -> Better performance
- Improved River generation. Rivers thickness can now be modified
- Fixed: Many buidlings were missing
- Fixed: Negative islands (Cutouts in elements) were creating floating objects when combining single-color-mode with a Text based shape
- Fixed: Some weird behaviour from the Single-color-mode on the outer rim
- Fixed: elements with "Separate objects" selected are now 1mm thick instead of having a flat bottom 
- Fixed: Wrong position of Roads and buiildings in 3mf export
- Fixed: Coloring Mountains behaved weirdly if it had multiple materials applied




Version 3.0
- Completely Restructured the Addon Code
- optimized Coloring Mountains for less color switches (Outside walls were always staying green before, now getting colored at treshold)
- Sliding/Jigzaw puzzles, Holders, connectors are now part of the Addon (Special category of the Advanced Tab)
- Sliding/Jigzaw puzzles are generated with just one click
- Sliding/Jigzaw puzzles are now compatible with Multi-generation
- More flexibility for Text Based Shapes
- Added Printable Icons to the Text Based Shapes
- Added SVG Import
- Added Custom Text Import
- Completely reworked the "Merge with Map" Function. Now 4 diffrent Options
    - Paint on Map
    - Project but keep as separate Object
    - Single-color-mode
    - Negative
- Added Roads
- Elements wont Generate if the Map area is too big to prevent Crashes (individual limit for each element)
- Objects are now properly getting cleared up when using x and y TerrainOffset
- Variable Aspect ratio for the Ellipse Shape
- Variable Width/Height for the Rectangle Shape (Previous only Squares possible)
- Replaced the Console Window with a Progress Bar
- Restructured the UI
- New Export format: .3mf (by downloading the 3mf Addon by Clonephaze)
- You can set a default Export older in the Addon preferences
- Oceans Beta
- Added Stone Elements (Mainly for mountain tips)
- Added Farmland elements
- Added Bevel setting to Plate Shapes (requested by @BH)
- Added Opentopography as another optional API for the elevation (thanks to @FLG)
- GPX files from more sources are now compatible
- option to disable auto 3mf Exports or automated exports
- Chinese and German Translation



'''

bl_info = {
    "name": "TrailPrint3D",
    "author": "EmGi",
    "version": (3, 0, 8),
    "blender": (4, 5, 0),
    "location": "View3D > Sidebar > TrailPrint3D",
    "description": "Create 3D Printable Miniature Maps of your Adventures",
    "warning": "",
    "doc_url": "https://www.trailprint3d.com",
    "tracker_url": "https://github.com/EmGi96/TrailPrint3D/issues",
    "category": "Object",
    "support": "COMMUNITY",
}

import bpy
import os

from . import translation
from . import constants as const
from . import temp
from . import addon_preferences
from . import props
from . import progress
from . import utils
from . import operators
from . import panels
from bpy.app.handlers import persistent

# Base (non-premium) classes — built once at import time.
# Premium classes are registered dynamically inside register() so that
# addon reload order (Blender may reload temp.py *after* __init__.py,
# resetting PREMIUMVERSION = False) cannot break detection.
classes = [
    progress.TP3D_OT_warnings_mouse,
    panels.TP3D_PT_generate,
    panels.TP3D_PT_advanced,
    panels.TP3D_PT_shapes,
    panels.TP3D_OT_show_custom_props_popup,
    operators.TP3D_OT_run_generation,
    operators.TP3D_OT_export_stl,
    operators.TP3D_OT_export_obj,
    operators.TP3D_OT_export_three_mf,
    operators.TP3D_OT_open_website,
    operators.TP3D_OT_join_discord,
    operators.TP3D_OT_rescale,
    operators.TP3D_OT_pin_coords,
    operators.TP3D_OT_terrain_dummy,
    operators.TP3D_OT_magnet_holes,
    operators.TP3D_OT_dovetail,
    operators.TP3D_OT_thicken,
    operators.TP3D_OT_bottom_mark,
    operators.TP3D_OT_color_mountain,
    operators.TP3D_OT_contour_lines,
    operators.TP3D_OT_save_preset,
    operators.TP3D_OT_load_preset,
    operators.TP3D_OT_delete_preset,
    operators.TP3D_OT_clear_cache,
    operators.TP3D_OT_import_svg,
    operators.TP3D_OT_popup_svg,
    operators.TP3D_OT_info_video,
    operators.TP3D_OT_popup_text,
    operators.TP3D_OT_import_text,
    operators.TP3D_OT_import_pin,
    operators.TP3D_OT_popup_pin,
    operators.TP3D_OT_popup_merge,
    operators.TP3D_OT_install_three_mf,
]

_PREMIUM_CLASS_NAMES = [
    "TP3D_OT_terrain",
    "TP3D_OT_chain_generation",
    "TP3D_OT_city_coords",
    "TP3D_OT_merge_with_map",
    "TP3D_OT_generate_just_trail",
    "TP3D_OT_from_center_generation",
    "TP3D_OT_from_center_generation_with_trail",
    "TP3D_OT_2point_generation",
    "TP3D_OT_special_collection",
    "TP3D_OT_append_collection",
    "TP3D_OT_append_collection_blank",
    "TP3D_OT_create_blank",
    "TP3D_OT_extend_tile",
    "TP3D_OT_import_height_map",
    "TP3D_OT_popup_heightmap",
]




@persistent
def startup_function(scene, dummy = None):

    print("Trailprint3D Launching Startup functions")
    
    utils.loadCollections(scene, dummy)

    utils.is_3mf_extension_installed()

    current = bpy.context.scene.preset_list
    #utils.load_myproperties_from_csv(current)

def register():
    # Ensure cache/preset dirs exist before anything else uses them.
    const._ensure_dirs()

    # Detect premium here — register() is called after Blender finishes reloading
    # all submodules, so temp.py can no longer reset PREMIUMVERSION to False after us.
    _addon_dir = os.path.dirname(__file__)
    temp.PREMIUMVERSION = os.path.exists(os.path.join(_addon_dir, "operators_pe.py"))

    ops_pe = None
    if temp.PREMIUMVERSION:
        try:
            import importlib
            importlib.import_module(".utils_pe", __package__)   # loads into sys.modules
            ops_pe = importlib.import_module(".operators_pe", __package__)
        except ImportError as e:
            print(f"TrailPrint3D: Error loading premium modules: {e}")
            temp.PREMIUMVERSION = False

    bpy.utils.register_class(addon_preferences.TP3D_AddonPreferences)
    bpy.utils.register_class(props.TP3D_PG_properties)
    bpy.app.translations.register(const.ADDON_NAME, translation.translations_dict)
    bpy.types.Scene.tp3d = bpy.props.PointerProperty(type=props.TP3D_PG_properties)
    bpy.types.Scene.preset_list = bpy.props.EnumProperty(
        name="Presets",
        items=utils.list_files_callback,
    )

    for cls in classes:
        bpy.utils.register_class(cls)

    if ops_pe:
        for name in _PREMIUM_CLASS_NAMES:
            cls = getattr(ops_pe, name, None)
            if cls:
                bpy.utils.register_class(cls)

    bpy.app.handlers.load_post.append(startup_function)

    # Populate special collections immediately so the UI isn't empty after a
    # reload. load_post only fires on the next file-open, so we schedule a
    # deferred call here that runs once the event loop is back and context is
    # fully available.
    bpy.app.timers.register(_load_collections_deferred, first_interval=0)


def _load_collections_deferred():
    try:
        utils.loadCollections(None, None)
    except Exception as e:
        print(f"TrailPrint3D: deferred collection load failed: {e}")
    return None   # returning None cancels the timer (run once)


def unregister():
    bpy.app.translations.unregister(const.ADDON_NAME)

    if temp.PREMIUMVERSION:
        import sys
        ops_pe = sys.modules.get(f"{__package__}.operators_pe")
        if ops_pe:
            for name in reversed(_PREMIUM_CLASS_NAMES):
                cls = getattr(ops_pe, name, None)
                if cls:
                    try:
                        bpy.utils.unregister_class(cls)
                    except Exception:
                        pass

    for cls in reversed(classes):
        try:
            bpy.utils.unregister_class(cls)
        except Exception:
            pass

    try:
        bpy.utils.unregister_class(props.TP3D_PG_properties)
    except Exception:
        pass

    try:
        bpy.utils.unregister_class(addon_preferences.TP3D_AddonPreferences)
    except Exception:
        pass

    try:
        bpy.app.handlers.load_post.remove(startup_function)
    except Exception:
        pass

    try:
        del bpy.types.Scene.tp3d
    except Exception:
        pass

    try:
        del bpy.types.Scene.preset_list
    except Exception:
        pass

