#  Copyright (C) 2026  EmGi

# You are free to modify it under the terms of the GNU General Public License as published by the Free Software Foundation.
# You are free to use any models Generated by this Addon Commercially

import bpy
from bpy.props import StringProperty


class TP3D_AddonPreferences(bpy.types.AddonPreferences):
    bl_idname = __package__

    default_export_folder: StringProperty(
        name="Default Export Folder",
        description="Default folder used when exporting STL / OBJ / 3MF files",
        default="",
        subtype='DIR_PATH',
    )  # type: ignore

    openTopographyApiKey: StringProperty(
        name="OpenTopography API Key",
        description="API key from portal.opentopography.org — free registration required for most datasets",
        default="",
    )  # type: ignore

    def draw(self, context):
        from . import temp
        layout = self.layout

        # Premium status
        box = layout.box()
        row = box.row()
        row.label(text="Premium Version:" if temp.PREMIUMVERSION else "Free Version", icon='CHECKMARK' if temp.PREMIUMVERSION else 'X')

        layout.separator()

        # OpenTopography API Key
        layout.label(text="OpenTopography API Key:", icon='INTERNET')
        layout.prop(self, "openTopographyApiKey", text="")
        if not self.openTopographyApiKey:
            layout.label(text="Required for most datasets — free at portal.opentopography.org", icon='ERROR')

        layout.separator()

        # Export
        layout.label(text="Export Settings:", icon='EXPORT')
        layout.prop(self, "default_export_folder")

        layout.separator()



def get_prefs():
    """Convenience helper — returns the AddonPreferences instance."""
    return bpy.context.preferences.addons[__package__].preferences
