#  Copyright (C) 2026  EmGi

# You are free to modify it under the terms of the GNU General Public License as published by the Free Software Foundation.
# You are free to use any models Generated by this Addon Commercially

import os
import platform
import sys
from collections import defaultdict

import bpy
from bpy.app.translations import (  # type: ignore
    pgettext_iface as _,  # For Translation of Text Required
)

ADDON_NAME = "TrailPrint3D"
ADDON_VERSION = (3, 2, 1)
required_blender_version = (5, 1, 0)

ENABLE_UPDATE_CHECKER = True

R = 6371.0  # Earth radius in kilometers

# -- Element size limits --

WATER_MAXSIZE = 500
SMALL_RIVERS_MAXSIZE = 50  # small/minor waterways drop out above this; big (wikidata) rivers + ponds still apply up to WATER_MAXSIZE
FOREST_MAXSIZE = 150
SCREE_MAXSIZE = 300
CITY_MAXSIZE = 50
GREENSPACE_MAXSIZE = 50
FARMLAND_MAXSIZE = 200
GLACIER_MAXSIZE = 1000
BUILDINGS_MAXSIZE = 30
BUILDINGS_MIN_PRINT_MM = 0.15  # PRINTED footprint
ROADS_MAXSIZE = 500
COASTLINE_MAXSIZE = 350
COASTLINE_WATERPOLY_MAXSIZE = 20000
STREETS_PRIMARY_THRESHOLD = (
    40  # dense-tier roads (residential/service/footway/cycle_bridle/path)
)

# -- Texture Constants --
_KIND_MATERIAL_NAME = {
    "WATER": "WATER",
    "OCEAN": "WATER",
    "FOREST": "FOREST",
    "SCREE": "MOUNTAIN",
    "CITY": "CITY",
    "GREENSPACE": "GREENSPACE",
    "FARMLAND": "FARMLAND",
    "GLACIER": "GLACIER",
    "ROADS": "BLACK",
    "TRAIL": "TRAIL",
}

# Rasterization order: low-priority kinds first so high-priority kinds
# overwrite them in overlap areas.  Mirrors the inverse of
# TERRAIN_PRIORITY_ORDER in generation.py.
_RASTER_ORDER = [
    "GLACIER",
    "FARMLAND",
    "GREENSPACE",
    "SCREE",
    "CITY",
    "FOREST",
    "OCEAN",
    "WATER",
    "ROADS",
    "TRAIL",
]

_UV_LAYER_NAME = "MMU_Paint"

_HEIGHT_BAKE_BASELINE = {}
_HEIGHT_BAKE_UNDO = defaultdict(list)
_MAX_HEIGHT_BAKE_UNDO_MEMORY = 64 * 1024 * 1024  # 64 MB

_LANDCOVER_COLOR_ROWS = (
    ("col_lcWaterActive", "WATER", _("Water")),
    ("col_lcForestActive", "FOREST", _("Forest")),
    ("col_lcMountainActive", "MOUNTAIN", _("Mountain")),
    ("col_lcCityActive", "CITY", _("City")),
    ("col_lcGreenspaceActive", "GREENSPACE", _("Greenspace")),
    ("col_lcFarmlandActive", "FARMLAND", _("Farmland")),
    ("col_lcGlacierActive", "GLACIER", _("Glacier")),
)

# -- Internal caches and special collections --

_elevation_cache = {}
specialCollection = []

# Define a path to store the counter data
counter_file = os.path.join(
    bpy.utils.user_resource("CONFIG"), "api_request_counter.json"
)

# Define a path to store the total maps generated counter
generation_counter_file = os.path.join(
    bpy.utils.user_resource("CONFIG"), "generation_counter.json"
)

# Set up a folder that holds all Cache Data
cache_dir = os.path.join(bpy.utils.user_resource("CONFIG"), "TrailPrint3D_Cache")

elevation_cache_file = os.path.join(
    bpy.utils.user_resource("CONFIG"), "TrailPrint3D_Cache", "elevation_cache.json"
)

# Set up a cache directory for Terrarium tiles
terrarium_cache_dir = os.path.join(
    bpy.utils.user_resource("CONFIG"), "TrailPrint3D_Cache", "terrarium_cache"
)

# Set up a cache for Overpass Files
overpass_cache_dir = os.path.join(
    bpy.utils.user_resource("CONFIG"), "TrailPrint3D_Cache", "overpass_cache"
)

# Set up a cache for computed elevation arrays (per-map vertex elevations)
elevation_results_dir = os.path.join(
    bpy.utils.user_resource("CONFIG"), "TrailPrint3D_Cache", "elevation_results"
)

# Set up a cache for downloaded satellite imagery crops
satellite_cache_dir = os.path.join(
    bpy.utils.user_resource("CONFIG"), "TrailPrint3D_Cache", "satellite_cache"
)

# Set up a cache for the global OSMData water-polygon dataset (downloaded zip is
# converted once to a WKB GeometryCollection and only the WKB is kept)
water_cache_dir = os.path.join(
    bpy.utils.user_resource("CONFIG"), "TrailPrint3D_Cache", "water_cache"
)

# Set up a folder for Presets
preset_dir = os.path.join(bpy.utils.user_resource("CONFIG"), "TP3D-presets")

# Set up a folder for the picker pages' (puzzleGenerator.html etc.) per-
# generator generation history -- one JSON file per page, see
# picker_server.py's /save_history_entry & /get_history.
generation_history_dir = os.path.join(bpy.utils.user_resource('CONFIG'), "TP3D-history")

# Real top-down Blender renders of past generations (export.save_history_thumbnail),
# named <history entry id>.png -- served by picker_server.py's
# /get_history_render once the generation that created them has actually
# finished, which is usually well after that picker session's own server
# already shut down.
generation_history_thumbnails_dir = os.path.join(generation_history_dir, "thumbnails")


def _ensure_dirs():
    """Create addon cache/preset directories. Call from register() only."""
    os.makedirs(cache_dir, exist_ok=True)
    os.makedirs(terrarium_cache_dir, exist_ok=True)
    os.makedirs(overpass_cache_dir, exist_ok=True)
    os.makedirs(elevation_results_dir, exist_ok=True)
    os.makedirs(satellite_cache_dir, exist_ok=True)
    os.makedirs(water_cache_dir, exist_ok=True)
    os.makedirs(preset_dir, exist_ok=True)
    os.makedirs(generation_history_dir, exist_ok=True)
    os.makedirs(generation_history_thumbnails_dir, exist_ok=True)


LINUX_PYTHON314_MISMATCH = platform.system() == "Linux" and sys.version_info[:2] == (
    3,
    14,
)
