#  Copyright (C) 2026  EmGi

# You are free to modify it under the terms of the GNU General Public License as published by the Free Software Foundation.
# You are free to use any models Generated by this Addon Commercially

import os

import bpy

ADDON_NAME = "TrailPrint3D"
ADDON_VERSION = (3, 2, 1)
required_blender_version = (5, 1, 0)

ENABLE_UPDATE_CHECKER = True

R = 6371.0  # Earth radius in kilometers

WATER_MAXSIZE = 500
SMALL_RIVERS_MAXSIZE = 50  # small/minor waterways drop out above this; big (wikidata) rivers + ponds still apply up to WATER_MAXSIZE
FOREST_MAXSIZE = 150
SCREE_MAXSIZE = 300
CITY_MAXSIZE = 50
GREENSPACE_MAXSIZE = 50
FARMLAND_MAXSIZE = 200
GLACIER_MAXSIZE = 1000
BUILDINGS_MAXSIZE = 30
BUILDINGS_MIN_PRINT_MM = 0.15 # Buildings whose PRINTED footprint side is smaller than this are culled, scales with map size.
ROADS_MAXSIZE = 500                  # dense + sparse road tiers dropped entirely above this mapsize
COASTLINE_MAXSIZE = 350
# Above COASTLINE_MAXSIZE, ocean is built from the prebuilt global OSMData
# water-polygon dataset (STRtree query, no Overpass fetch) instead of being
# skipped outright. The dataset itself is only meant for zoom 0-9 (i.e. large
# / low-detail views), which is exactly the map-size regime this covers, so
# there's no strong reason to cap it the way the Overpass path is capped --
# leave generous headroom and tighten later if profiling on a real huge map
# says otherwise.
COASTLINE_WATERPOLY_MAXSIZE = 20000
STREETS_PRIMARY_THRESHOLD = 40       # dense-tier roads (residential/service/footway/cycle_bridle/path)
                                      # dropped above this mapsize to avoid width-scaled roads fusing
                                      # into solid blocks on zoomed-out maps; sparse tiers (highways/
                                      # major/minor/track) are unaffected until ROADS_MAXSIZE



_elevation_cache = {}
specialCollection = []

# Define a path to store the counter data
counter_file = os.path.join(bpy.utils.user_resource('CONFIG'), "api_request_counter.json")

# Define a path to store the total maps generated counter
generation_counter_file = os.path.join(bpy.utils.user_resource('CONFIG'), "generation_counter.json")

#Set up a folder that holds all Cache Data
cache_dir = os.path.join(bpy.utils.user_resource('CONFIG'), "TrailPrint3D_Cache")

elevation_cache_file = os.path.join(bpy.utils.user_resource('CONFIG'), "TrailPrint3D_Cache","elevation_cache.json")

# Set up a cache directory for Terrarium tiles
terrarium_cache_dir = os.path.join(bpy.utils.user_resource('CONFIG'), "TrailPrint3D_Cache","terrarium_cache")

# Set up a cache for Overpass Files
overpass_cache_dir = os.path.join(bpy.utils.user_resource('CONFIG'), "TrailPrint3D_Cache","overpass_cache")

# Set up a cache for computed elevation arrays (per-map vertex elevations)
elevation_results_dir = os.path.join(bpy.utils.user_resource('CONFIG'), "TrailPrint3D_Cache","elevation_results")

# Set up a cache for downloaded satellite imagery crops
satellite_cache_dir = os.path.join(bpy.utils.user_resource('CONFIG'), "TrailPrint3D_Cache","satellite_cache")

# Set up a cache for the global OSMData water-polygon dataset (downloaded zip is
# converted once to a WKB GeometryCollection and only the WKB is kept)
water_cache_dir = os.path.join(bpy.utils.user_resource('CONFIG'), "TrailPrint3D_Cache","water_cache")

#Set up a folder for Presets
preset_dir = os.path.join(bpy.utils.user_resource('CONFIG'), "TP3D-presets")


def _ensure_dirs():
    """Create addon cache/preset directories. Call from register() only."""
    os.makedirs(cache_dir, exist_ok=True)
    os.makedirs(terrarium_cache_dir, exist_ok=True)
    os.makedirs(overpass_cache_dir, exist_ok=True)
    os.makedirs(elevation_results_dir, exist_ok=True)
    os.makedirs(satellite_cache_dir, exist_ok=True)
    os.makedirs(water_cache_dir, exist_ok=True)
    os.makedirs(preset_dir, exist_ok=True)



