#  Copyright (C) 2026  EmGi

# You are free to modify it under the terms of the GNU General Public License as published by the Free Software Foundation.
# You are free to use any models Generated by this Addon Commercially

import bpy
import os

ADDON_NAME = "TrailPrint3D"
ADDON_VERSION = (3, 0, 8)
required_blender_version = (4, 5, 0)

R = 6371.0  # Earth radius in kilometers

WATER_MAXSIZE = 5000
FOREST_MAXSIZE = 1000
SCREE_MAXSIZE = 1000
CITY_MAXSIZE = 1000
GREENSPACE_MAXSIZE = 50
FARMLAND_MAXSIZE = 1000
GLACIER_MAXSIZE = 1000
BUILDINGS_MAXSIZE = 30
ROADS_MAXSIZE = 500
STREETS_MAJOR_ONLY_THRESHOLD = 100   # above this mapsize: motorway+trunk only
STREETS_PRIMARY_THRESHOLD = 40       # above this mapsize: + primary+secondary

_elevation_cache = {}
specialCollection = []

# Define a path to store the counter data
counter_file = os.path.join(bpy.utils.user_resource('CONFIG'), "api_request_counter.json")

#Set up a folder that holds all Cache Data
cache_dir = os.path.join(bpy.utils.user_resource('CONFIG'), "TrailPrint3D_Cache")
if not os.path.exists(cache_dir):
    os.makedirs(cache_dir)

elevation_cache_file = os.path.join(bpy.utils.user_resource('CONFIG'), "TrailPrint3D_Cache","elevation_cache.json")

# Set up a cache directory for Terrarium tiles
terrarium_cache_dir = os.path.join(bpy.utils.user_resource('CONFIG'), "TrailPrint3D_Cache","terrarium_cache")
if not os.path.exists(terrarium_cache_dir):
    os.makedirs(terrarium_cache_dir)

# Set up a cache for Overpass Files
overpass_cache_dir = os.path.join(bpy.utils.user_resource('CONFIG'), "TrailPrint3D_Cache","overpass_cache")
if not os.path.exists(overpass_cache_dir):
    os.makedirs(overpass_cache_dir)

#Set up a folder for Presets
preset_dir = os.path.join(bpy.utils.user_resource('CONFIG'), "TP3D-presets")
if not os.path.exists(preset_dir):
    os.makedirs(preset_dir)



