#  Copyright (C) 2026  EmGi

# You are free to modify it under the terms of the GNU General Public License as published by the Free Software Foundation.
# You are free to use any models Generated by this Addon Commercially


import bpy  # type: ignore
from mathutils import Vector  # type: ignore

from . import addon_preferences, temp
from . import progress as _progress
from .threemf_discovery import (
    get_threemf_api,
    has_threemf_capability,
    is_threemf_available,
)


def _sanitize_filename(name):
    invalid = r'\/:*?"<>|'
    for ch in invalid:
        name = name.replace(ch, "_")
    return name


def export_to_STL(zobj, force="STL"):

    exportPath = bpy.context.scene.tp3d.get('export_path', None)
    if not exportPath:
        exportPath = addon_preferences.get_prefs().default_export_folder
    if not exportPath:
        _progress.WarningsOverlay.add_warning("Export folder not set — please set an export path", "error")
        return
    bpy.ops.object.select_all(action='DESELECT')
    zobj.select_set(True)
    bpy.context.view_layer.objects.active = zobj

    if zobj.material_slots and force != "STL":
        bpy.ops.wm.obj_export(filepath=exportPath + _sanitize_filename(zobj.name) + ".obj",
            export_selected_objects=True,
            export_triangulated_mesh=True,
            apply_modifiers=True,
            export_materials=True,
            forward_axis="Y",
            up_axis="Z",
            )
    else:
        bpy.ops.wm.stl_export(filepath=exportPath + _sanitize_filename(zobj.name) + ".stl", export_selected_objects=True)

    zobj.select_set(False)  # Select the object


def export_selected_to_STL(force="STL"):
    from .utils import show_message_box

    exportPath = bpy.context.scene.tp3d.get('export_path', None)
    if not exportPath:
        exportPath = addon_preferences.get_prefs().default_export_folder
    if not exportPath:
        _progress.WarningsOverlay.add_warning("Export folder not set — please set an export path", "error")
        return {'FINISHED'}
    selected_objects = bpy.context.selected_objects
    active_obj = bpy.context.active_object

    if not selected_objects:
            show_message_box("No objects selected")
            return{'FINISHED'}

    for zobj in selected_objects:
        bpy.ops.object.select_all(action='DESELECT')
        zobj.select_set(True)
        bpy.context.view_layer.objects.active = zobj

        if (zobj.material_slots or force == "OBJ") and force != "STL":
            bpy.ops.wm.obj_export(filepath=exportPath + _sanitize_filename(zobj.name) + ".obj",
                export_selected_objects=True,
                export_triangulated_mesh=True,
                apply_modifiers=True,
                export_materials=True,
                forward_axis="Y",
                up_axis="Z",
                )
            #show_message_box("File Exported as OBJ because it contains Materials","INFO","OBJ File Exported")
        else:
            bpy.ops.wm.stl_export(filepath=exportPath + _sanitize_filename(zobj.name) + ".stl", export_selected_objects=True)


    bpy.ops.object.select_all(action='DESELECT')
    for zobj in selected_objects:
        zobj.select_set(True)
    bpy.context.view_layer.objects.active = active_obj


    active_obj = bpy.context.active_object


def export_selected_to_3mf(filename: str = "", is_auto: bool = False):
    import os
    import tempfile

    from mathutils import Vector

    from .utils import show_message_box

    exportPath = bpy.context.scene.tp3d.get('export_path', "")
    if not exportPath:
        exportPath = addon_preferences.get_prefs().default_export_folder
    if not exportPath:
        _progress.WarningsOverlay.add_warning("Export folder not set — please set an export path", "error")
        return {'FINISHED'}

    selected_objects = bpy.context.selected_objects
    if not selected_objects:
        show_message_box("No objects selected")
        return {'FINISHED'}

    # 1. Duplicate all selected objects + children (preserve hierarchy)
    all_to_export = list(selected_objects)
    for obj in selected_objects:
        for child in obj.children_recursive:
            if child not in all_to_export:
                all_to_export.append(child)

    original_to_dup = {}
    duplicates = []
    scene_col = bpy.context.scene.collection
    for obj in all_to_export:
        dup = obj.copy()
        dup.data = obj.data.copy() if obj.data else None
        scene_col.objects.link(dup)
        original_to_dup[obj] = dup
        duplicates.append(dup)

    # Re-establish parent relationships
    for orig, dup in original_to_dup.items():
        if orig.parent in original_to_dup:
            dup.parent = original_to_dup[orig.parent]
            dup.matrix_parent_inverse = orig.matrix_parent_inverse.copy()
        else:
            dup.parent = None
            dup.matrix_world = orig.matrix_world.copy()

    # Convert curves to mesh
    for obj in duplicates:
        if obj.type == 'CURVE':
            bpy.ops.object.select_all(action='DESELECT')
            obj.select_set(True)
            bpy.context.view_layer.objects.active = obj
            bpy.ops.object.convert(target='MESH')

    # With texture-mode paint export, companion objects (text/plate/shell, and
    # the trail when it's excluded from the baked texture) have no paint data
    # of their own -- give each a solid-colour paint texture matching the
    # terrain's own baked palette so the exporter doesn't default them all to
    # extruder 1. Done here (not at generation time) so it's also correct on
    # a plain re-export of an already-generated map, not just a fresh one.
    tp3d = bpy.context.scene.tp3d
    if tp3d.tex_use_texture:
        import ast

        from .utils.texture import (
            _srgb_to_hex,
            material_to_srgb,
            tag_solid_color_for_paint_export,
        )

        map_dup = next((d for d in duplicates if d.get("Object type") == "MAP"), None)
        if map_dup is not None and map_dup.type == 'MESH':
            try:
                palette = ast.literal_eval(map_dup.data.get("3mf_paint_extruder_colors", "{}"))
            except (ValueError, SyntaxError):
                palette = {}
            if palette:
                # TEXT/PLATE/SHELL are always one fixed colour; TRAIL is not --
                # different trail curves can carry different materials (e.g. a
                # red vs. a yellow trail), so that one must be read from each
                # object's own material rather than assumed to be constant.
                _fixed_companion_material = {"TEXT": "WHITE", "PLATE": "BLACK", "SHELL": "BLACK"}
                _palette_dirty = False
                for dup in duplicates:
                    obj_type = dup.get("Object type")
                    if obj_type in _fixed_companion_material:
                        _ccol = material_to_srgb(bpy.data.materials.get(_fixed_companion_material[obj_type]))
                    elif obj_type == "TRAIL" and not tp3d.tex_include_trail:
                        _own_mat = dup.data.materials[0] if dup.data and dup.data.materials else None
                        _ccol = material_to_srgb(_own_mat or bpy.data.materials.get("TRAIL"))
                    else:
                        continue
                    _chex = _srgb_to_hex(*_ccol)
                    if _chex not in palette.values():
                        palette[max(palette.keys()) + 1] = _chex
                        _palette_dirty = True
                    tag_solid_color_for_paint_export(dup, _ccol, palette)
                if _palette_dirty:
                    map_dup.data["3mf_paint_extruder_colors"] = str(palette)

    # ------------------------------------------------------------------
    #  New grouping logic based on tp3d.keep_positions
    # ------------------------------------------------------------------
    temp_empties = []          # we'll delete these later
    if bpy.context.scene.tp3d.keep_positions:
        # Group ALL objects under one root, preserve world transforms
        root_empty = bpy.data.objects.new("TP3D_Group", None)
        bpy.context.collection.objects.link(root_empty)
        temp_empties.append(root_empty)

        # Only top‑level objects get parented to the root; children keep their original parent
        top_level = [obj for obj in duplicates if obj.parent is None]
        for obj in top_level:
            obj.parent = root_empty
            # Adjust inverse matrix so world transform stays unchanged
            obj.matrix_parent_inverse = root_empty.matrix_world.inverted() @ obj.matrix_world

        export_roots = [root_empty]   # only one root object to export

    else:
        # Original behaviour: center, group by "ExportGroup" custom property
        center = get_selection_center(duplicates)
        offset = Vector((-center.x, -center.y, -center.z))
        for obj in duplicates:
            obj.location += offset

        groups = {}
        ungrouped = []
        for obj in duplicates:
            group_id = obj.get("ExportGroup", 0)
            if group_id > 0:
                groups.setdefault(group_id, []).append(obj)
            else:
                ungrouped.append(obj)

        GROUP_NAMES = ["Map", "Plate"]
        export_roots = []
        for idx, (g_id, members) in enumerate(sorted(groups.items())):
            if len(members) == 1:
                export_roots.append(members[0])
                continue
            empty = bpy.data.objects.new(
                GROUP_NAMES[idx] if idx < len(GROUP_NAMES) else f"Group_{g_id}",
                None
            )
            bpy.context.collection.objects.link(empty)
            temp_empties.append(empty)
            export_roots.append(empty)
            for member in members:
                member.parent = empty

        export_roots.extend(ungrouped)

    # ------------------------------------------------------------------
    #  Thumbnail & export (unchanged)
    # ------------------------------------------------------------------
    thumbnail_path = os.path.join(tempfile.gettempdir(), "tp3d_thumbnail.png")
    if not bpy.app.background:
        customThumbnail(duplicates, thumbnail_path)

    base_name = filename if filename else bpy.context.scene.tp3d.modelname
    full_path = exportPath + _sanitize_filename(base_name) + ".3mf"

    _3mf_api = get_threemf_api()
    if _3mf_api is None:
        _progress.WarningsOverlay.add_warning("3MF Addon not installed", "error")
        return

    try:
        tp3d = bpy.context.scene.tp3d
        _is_texture_mode: bool = tp3d.tex_use_texture
        _on_progress = None
        if is_auto:
            _overlay = _progress.ProgressOverlay.get()
            def _on_progress(percent: int, message: str) -> None:
                _overlay.update(0.97 + (percent / 100.0) * 0.03, "3MF Export", message)

        export_kwargs = dict(
            filepath=full_path,
            objects=export_roots,
            use_mesh_modifiers=True,
            global_scale=0.001,
            coordinate_precision=4,
            thumbnail_mode="NONE" if bpy.app.background else "CUSTOM",
            thumbnail_image=thumbnail_path if not bpy.app.background else "",
            thumbnail_resolution=256,
            use_orca_format="PAINT" if _is_texture_mode else "AUTO",
            progress_mode="NONE" if is_auto else "AUTO",
            on_progress=_on_progress,
        )
        if has_threemf_capability("slicer_profile"):
            export_kwargs["slicer_profile"] = tp3d.slicer_profile_name
        else:
            _progress.WarningsOverlay.add_warning("3MF Addon update available (slicer profiles)", "warn")

        result = _3mf_api.export_3mf(**export_kwargs)
        if result.status == "FINISHED":
            print(f"Successfully exported to: {full_path}")
            _progress.WarningsOverlay.add_warning("Exported as 3mf", "ok")
        else:
            print("Export Error:\n" + "\n".join(result.warnings))
            _progress.WarningsOverlay.add_warning("Exporting as 3mf Failed", "error")
    except Exception as e:
        print(f"Export Error: {e}")
        _progress.WarningsOverlay.add_warning("Exporting as 3mf Failed", "error")

    # 5. Cleanup (delete duplicates and temporary empties)
    for obj in duplicates + temp_empties:
        if obj is None:
            continue
        for col in obj.users_collection:
            col.objects.unlink(obj)
        bpy.data.objects.remove(obj)

    return {'FINISHED'}

def customThumbnail(objects, output_path, resolution=256):
    scene = bpy.context.scene

    # 1. Setup Render Resolution
    orig_x = scene.render.resolution_x
    orig_y = scene.render.resolution_y
    scene.render.resolution_x = resolution
    scene.render.resolution_y = resolution
    scene.render.resolution_percentage = 100

    # 2. Find 3D View (Crucial for saving state)
    area = next((a for a in bpy.context.screen.areas if a.type == 'VIEW_3D'), None)
    if not area:
        return # Safety exit

    space = area.spaces.active
    rv3d = space.region_3d

    # 3. SAVE INITIAL STATE (Pixel-perfect)
    old_camera = scene.camera
    old_shading = space.shading.type
    old_overlay = space.overlay.show_overlays
    old_view_matrix = rv3d.view_matrix.copy() # Saves rotation/zoom
    old_perspective = rv3d.view_perspective

    # 4. Setup Temporary Camera
    tmp_cam_data = bpy.data.cameras.new("TempTopCam")
    tmp_cam_data.type = 'ORTHO'
    tmp_cam_obj = bpy.data.objects.new("TempTopCam", tmp_cam_data)
    scene.collection.objects.link(tmp_cam_obj)

    # Position: High up, looking straight down
    tmp_cam_obj.location = (0, 0, 100)
    tmp_cam_obj.rotation_euler = (0, 0, 0)
    scene.camera = tmp_cam_obj

    # 5. Set Viewport for Render
    space.shading.type = 'MATERIAL'
    space.overlay.show_overlays = False

    # 6. Selection & Framing
    bpy.ops.object.select_all(action='DESELECT')
    for obj in objects:
        obj.select_set(True)

    # 7. Execute Render with Override
    with bpy.context.temp_override(area=area, region=area.regions[-1]):
        # Snap view to the temp camera
        rv3d.view_perspective = 'CAMERA'

        # Zoom camera to fit objects
        bpy.ops.view3d.camera_to_view_selected()

        # Render the viewport
        scene.render.filepath = output_path
        bpy.ops.render.opengl(write_still=True, view_context=True)

    # 8. RESTORE INITIAL STATE
    scene.camera = old_camera
    space.shading.type = old_shading
    space.overlay.show_overlays = old_overlay

    # Use the saved matrix to teleport the view back
    rv3d.view_matrix = old_view_matrix
    rv3d.view_perspective = old_perspective

    # Update resolution
    scene.render.resolution_x = orig_x
    scene.render.resolution_y = orig_y

    # Cleanup camera data
    bpy.data.objects.remove(tmp_cam_obj, do_unlink=True)
    bpy.data.cameras.remove(tmp_cam_data, do_unlink=True)


def get_selection_center(objects):
    if not objects:
        return Vector((0, 0, 0))

    all_coords = []

    for obj in objects:
        # Get all 8 corners of the bounding box in World Space
        # matrix_world @ corner converts local box to world position
        bbox_corners = [obj.matrix_world @ Vector(corner) for corner in obj.bound_box]
        all_coords.extend(bbox_corners)

    # Find the min and max for each axis across ALL objects
    min_x = min(c.x for c in all_coords)
    max_x = max(c.x for c in all_coords)

    min_y = min(c.y for c in all_coords)
    max_y = max(c.y for c in all_coords)

    min_z = min(c.z for c in all_coords)

    center = Vector((
        (min_x + max_x) / 2,
        (min_y + max_y) / 2,
        min_z,
    ))

    return center


def is_3mf_extension_installed():
    is_en = is_threemf_available()
    temp.has3mf = is_en
    return is_en


#Install 3mf Addon
def install_3mf_extension():
    try:
        bpy.ops.extensions.package_install(pkg_id="ThreeMF_io")
        return True
    except RuntimeError as e:
        print(f"Installation failed: {e}")
        return False
