#  Copyright (C) 2026  EmGi

# You are free to modify it under the terms of the GNU General Public License as published by the Free Software Foundation.
# You are free to use any models Generated by this Addon Commercially

import bpy
import os

import bmesh # type: ignore
import math
from mathutils import Quaternion, Vector, Euler

from . import constants as const
from . import utils
from . import props
from . import addon_preferences

from bpy.props import StringProperty

from bpy.app.translations import pgettext_iface as _ #For Translation of Text Required


# Define the operator (script execution)
class TP3D_OT_run_generation(bpy.types.Operator):
    bl_idname = "tp3d.run_generation"
    bl_label = "Generate"
    bl_description = "Generate the Path and the Map with current Settings"

    def execute(self, context):
        tp3d = context.scene.tp3d  # Access stored variables
        
        utils.runGeneration(0)
        
        return {'FINISHED'}

class TP3D_OT_export_stl(bpy.types.Operator):
    bl_idname = "tp3d.export_stl"
    bl_label = "Export STL"
    bl_description = "Export Selected Objects as Separate STL (Will lose Colors)"

    def execute(self, context):
        tp3d = context.scene.tp3d  # Access stored variables

        exportPath = tp3d.get('export_path', None)

        if not exportPath:
            exportPath = addon_preferences.get_prefs().default_export_folder

        if not exportPath:
            self.report({'ERROR'}, "'Export path' is Empty. Please select a Directory For the finished files")
            return {'CANCELLED'}

        exportPath = bpy.path.abspath(exportPath)

        if not exportPath or exportPath == "":
            self.report({'ERROR'}, "Export path is empty! Please select a valid folder.")
            return {'CANCELLED'}
        if not os.path.isdir(exportPath):
            self.report({'ERROR'}, f"Invalid export Directory: {exportPath}. Please select a valid Directory.")
            return {'CANCELLED'}

        if not context.selected_objects:
            self.report({'ERROR'}, "Please select the Object you want to Export")
            return {'CANCELLED'}

        utils.export_selected_to_STL("STL")

        
        return {'FINISHED'}
    
class TP3D_OT_export_obj(bpy.types.Operator):
    bl_idname = "tp3d.export_obj"
    bl_label = "Export OBJ"
    bl_description = "Export Selected Objects as Separate OBJ"

    def execute(self, context):
        tp3d = context.scene.tp3d  # Access stored variables

        exportPath = tp3d.get('export_path', None)

        if not exportPath:
            exportPath = addon_preferences.get_prefs().default_export_folder

        if not exportPath:
            self.report({'ERROR'}, "'Export path' is Empty. Please select a Directory For the finished files")
            return {'CANCELLED'}

        exportPath = bpy.path.abspath(exportPath)

        if not exportPath or exportPath == "":
            self.report({'ERROR'}, "Export path is empty! Please select a valid folder.")
            return {'CANCELLED'}
        if not os.path.isdir(exportPath):
            self.report({'ERROR'}, f"Invalid export Directory: {exportPath}. Please select a valid Directory.")
            return {'CANCELLED'}

        if not context.selected_objects:
            self.report({'ERROR'}, "Please select the Object you want to Export")
            return {'CANCELLED'}

        utils.export_selected_to_STL("OBJ")

        
        return {'FINISHED'}

class TP3D_OT_export_three_mf(bpy.types.Operator):
    bl_idname = "tp3d.export_three_mf"
    bl_label = "Export 3mf"
    bl_description = "Export Selected Objects as Separate 3MF"

    def execute(self, context):
        tp3d = context.scene.tp3d  # Access stored variables

        installed = utils.is_3mf_extension_installed()

        if installed == True:
        
            exportPath = tp3d.get('export_path', None)

            if not exportPath:
                exportPath = addon_preferences.get_prefs().default_export_folder

            if not exportPath:
                self.report({'ERROR'}, "'Export path' is Empty. Please select a Directory For the finished files")
                return {'CANCELLED'}

            exportPath = bpy.path.abspath(exportPath)

            if not exportPath or exportPath == "":
                self.report({'ERROR'}, "Export path is empty! Please select a valid folder.")
                return {'CANCELLED'}
            if not os.path.isdir(exportPath):
                self.report({'ERROR'}, f"Invalid export Directory: {exportPath}. Please select a valid Directory.")
                return {'CANCELLED'}
            
            if not context.selected_objects:
                self.report({'ERROR'}, "Please select the Object you want to Export")
                return {'CANCELLED'}
            
            utils.export_selected_to_3mf()
        else:
            print("Addon not Installed")

        

        return {'FINISHED'}


class TP3D_OT_open_website(bpy.types.Operator):
    bl_idname = "tp3d.open_website"
    bl_label = "Visit My Website"
    bl_description = "The Patreon Version has Additional Features!"

    def execute(self, context):
        utils.open_website(self, context)
        return {'FINISHED'}
    

# Operator to open a website
class TP3D_OT_join_discord(bpy.types.Operator):
    bl_idname = "tp3d.join_discord"
    bl_label = "Join Discord"
    bl_description = "Discord Community for TrailPrint3D!"

    def execute(self, context):
        utils.open_website(self, context, "https://discord.gg/C67H9EJFbz")
        return {'FINISHED'}

# Operator to open a website
class TP3D_OT_info_video(bpy.types.Operator):
    bl_idname = "tp3d.info_video"
    bl_label = "Tutorial Video"
    bl_description = "Link to Video explaining this Feature"

    url: bpy.props.StringProperty(name="Url", default = "")  # type: ignore

    def execute(self, context):
        

        utils.open_website(self, context, self.url)
        return {'FINISHED'}
    
class TP3D_OT_rescale(bpy.types.Operator):
    bl_idname = "tp3d.rescale"
    bl_label = "Rescale the z value"
    bl_description = "Rescales the Elevation the Currently selected objects"
    bl_options = {'REGISTER', 'UNDO'}

    def execute(self, context):
        multiZ = context.scene.tp3d.get('rescaleMultiplier', 1)

        selected_objects = [obj for obj in bpy.context.selected_objects if obj.type in {'MESH', 'CURVE'}]
        lowestZ = 1000

        print("Rescaling")
        for obj in selected_objects:
            if obj.type == 'MESH':
                mesh = obj.data
                for i, vert in enumerate(mesh.vertices):
                    if vert.co.z < lowestZ and vert.co.z > 0.1:
                        lowestZ = vert.co.z
            if obj.type == "CURVE":
                if lowestZ == 1000:
                    for spline in obj.data.splines:
                        for point in spline.bezier_points:
                            if point.co.z > 0.1 and point.co.z < lowestZ:
                                lowestZ = point.co.z

        print(f"lowestZ: {lowestZ}")

        for obj in selected_objects:      
            print(obj.name)
            if lowestZ != 1000 and obj.type == "MESH":
                    bpy.context.view_layer.objects.active = obj  # Make it active
                    bpy.ops.object.mode_set(mode='EDIT')
                    # Access mesh data
                    mesh = bmesh.from_edit_mesh(obj.data)
                    for v in mesh.verts:
                        if v.co.z > 0.1:
                            v.co.z = (v.co.z - lowestZ) * (multiZ) + lowestZ
                    bmesh.update_edit_mesh(obj.data)    
                    bpy.ops.object.mode_set(mode='OBJECT')  # Exit Edit Mode  
            if lowestZ != 1000 and obj.type =="CURVE":
                # Access curve splines
                for spline in obj.data.splines:
                    for point in spline.bezier_points:
                        if point.co.z > -0.5:
                            point.co.z = (point.co.z - lowestZ) * (multiZ) + lowestZ
                    for point in spline.points:  # For NURBS
                        if point.co.z > -0.5:
                            point.co.z = (point.co.z - lowestZ) * (multiZ) + lowestZ

            bpy.ops.object.mode_set(mode='OBJECT')  # Exit Edit Mode

            if "Elevation Scale" in obj:
                obj["Elevation Scale"] *= multiZ

        print(f"Scaled all elevation points by Factor {multiZ} on {len(selected_objects)} object(s).")

        return {'FINISHED'}
    
class TP3D_OT_save_preset(bpy.types.Operator):
    bl_idname = "tp3d.save_preset"
    bl_label = _("Save preset")
    bl_description = "Save the current settings as a preset"
    bl_options = {'REGISTER', 'UNDO'}

    user_input: StringProperty(name="Preset name") # type: ignore

    def invoke(self, context, event):
        return context.window_manager.invoke_props_dialog(self)

    def draw(self, context):
        layout = self.layout
        layout.prop(self, "user_input")
    
    def execute(self,context):



        utils.save_myproperties_to_csv(self.user_input)

        utils.show_message_box("Saved Preset","CHECKMARK", " ")

        return {'FINISHED'}

class TP3D_OT_load_preset(bpy.types.Operator):
    bl_idname = "tp3d.load_preset"
    bl_label = _("Load preset")
    bl_description = "Load the current settings as a preset"
    bl_options = {'REGISTER', 'UNDO'}
    
    def execute(self,context):
        current = bpy.context.scene.preset_list
        utils.load_myproperties_from_csv(current)

        utils.show_message_box("Preset Loaded","CHECKMARK", " ")

        return {'FINISHED'}

class TP3D_OT_delete_preset(bpy.types.Operator):
    bl_idname = "tp3d.delete_preset"
    bl_label = _("Delete preset")
    bl_description = "Delete the current selected preset"
    bl_options = {'REGISTER', 'UNDO'}
    
    def execute(self,context):
        current = bpy.context.scene.preset_list
        utils.delete_preset_file(current)

        utils.show_message_box("Deleted Selected Preset","CHECKMARK", " ")

        return {'FINISHED'}

class TP3D_OT_clear_cache(bpy.types.Operator):
    bl_idname = "tp3d.clear_cache"
    bl_label = "Clear Cache"
    bl_description = "Delete all Cached Files from API calls"
    bl_options = {'REGISTER', 'UNDO'}


    def execute(self, context):
        """Delete all cached API files for this addon."""


        if not os.path.exists(const.cache_dir):
            print("Cache directory does not exist, nothing to clear.")
            return {'FINISHED'}

        count = 0
        for filename in os.listdir(const.cache_dir):
            file_path = os.path.join(const.cache_dir, filename)
            if os.path.isfile(file_path) and filename.endswith(".json"):
                try:
                    os.remove(file_path)
                    count += 1
                except Exception as e:
                    print(f"Failed to delete {file_path}: {e}")

        print(f"Cleared {count} cached Overpass files from {const.cache_dir}")
        return {'FINISHED'}


class TP3D_OT_thicken(bpy.types.Operator):
    bl_idname = "tp3d.thicken"
    bl_label = "Thicken Map"
    bl_description = "Make the selected Map thicker"
    bl_options = {'REGISTER', 'UNDO'}

    def execute(self,context):
        
        selected_objects = context.selected_objects
        val = context.scene.tp3d.thickenValue

        bpy.context.tool_settings.mesh_select_mode = (False, False, True)

        bpy.ops.object.select_all(action='DESELECT')
        for zobj in selected_objects:
            zobj.select_set(False)

        if not selected_objects:
            utils.show_message_box("No objects selected.")
            return {'CANCELLED'}

        for zobj in selected_objects:
            # Check if the custom property 'Object type' exists
            if "Object type" in zobj:
                print(zobj.name)
                if zobj["Object type"] == "TRAIL" or zobj["Object type"] == "WATER" or zobj["Object type"] == "FOREST" or zobj["Object type"] == "CITY" or zobj["Object type"] == "FARMLAND" or zobj["Object type"] == "GREENSPACE":
                    zobj.location.z += val
                elif zobj["Object type"] == "MAP" :
                    zobj.select_set(True)
                    bpy.context.view_layer.objects.active = zobj
                    utils.selectBottomFaces(zobj)
                    bpy.ops.mesh.select_more()
                    bpy.ops.mesh.select_all(action='INVERT')
                    mesh = bmesh.from_edit_mesh(zobj.data)
                    
                    verts_to_move = set()
                    for face in mesh.faces:
                        if face.select:
                            verts_to_move.update(face.verts)

                    for vert in verts_to_move:
                        vert.co.z += val
                    bpy.ops.object.mode_set(mode='OBJECT')
                    bpy.ops.object.select_all(action='DESELECT')
                    zobj.select_set(False)
                    zobj["minThickness"] += val
                    
        bpy.context.view_layer.objects.active = selected_objects[0]
        for zobj in selected_objects:
            zobj.select_set(True)

                    


        return {'FINISHED'}

class TP3D_OT_pin_coords(bpy.types.Operator):
    bl_idname = "tp3d.pin_coords"
    bl_label = "PinCoords"
    bl_description = "Place a Pin on a Coordinate"
    bl_options = {'REGISTER', 'UNDO'}

    def execute(self, context):
        tp3d = context.scene.tp3d
        
        minThickness = tp3d.minThickness

        centerlat = tp3d.pinLat
        centerlon = tp3d.pinLon



        xp,yp,zp = utils.convert_to_blender_coordinates(float(centerlat),float(centerlon),0,0)
        name = "Pin_" + str(round(centerlat,2)) + "." + str(round(centerlon,2))

        #Delete existing object with same name (optional)
        if name in bpy.data.objects:
            bpy.data.objects.remove(bpy.data.objects[name], do_unlink=True)

        # Get map object for raycasting
        map_obj = None
        active = context.view_layer.objects.active
        if active and "objSize" in active.keys():
            map_obj = active
        elif context.scene.tp3d.currentMap:
            map_obj = context.scene.tp3d.currentMap

        # Determine Z: raycast onto map surface, fallback to minThickness
        pin_z = minThickness + 2
        if map_obj:
            hit_z = utils.RaycastPointToMeshZ((xp, yp, 0), map_obj)
            if hit_z is not None:
                pin_z = hit_z + 1  # cone center 1mm below surface

        #Creatin the Cone
        bpy.ops.mesh.primitive_cone_add(
            vertices=16,
            radius1=0.4,
            radius2=0.8,
            depth=4,
            location=(xp, yp, pin_z)
        )
        pin = bpy.context.active_object
        pin.name = name
        mat = bpy.data.materials.get("TRAIL")
        if mat:
            pin.data.materials.append(mat)

        return {'FINISHED'}

class TP3D_OT_magnet_holes(bpy.types.Operator):
    bl_idname = "tp3d.magnet_holes"
    bl_label = "Magnet Holes"
    bl_options = {'REGISTER', 'UNDO'}


    
    def execute(self,context):
        tp3d = context.scene.tp3d

        selected_objects = context.selected_objects

        if not selected_objects:
            utils.show_message_box("No objects selected")
            #return{'FINISHED'}
            return{'FINISHED'}
        
        
        bpy.ops.object.select_all(action='DESELECT')
        for zobj in selected_objects:
            zobj.select_set(False)

        for zobj in selected_objects:

            if zobj.type != 'MESH':
                continue

            zobj.select_set(True)
            bpy.context.view_layer.objects.active = zobj

            obj_size = tp3d.objSize

            #Check for selection and custom property
            if zobj:
                if "objSize" in zobj.keys():
                    obj_size = zobj["objSize"]
            elif not zobj:
                    print("Select a Map.")
                    return{'FINISHED'}
            
            if "MagnetHoles" not in zobj.keys():
                continue

            if zobj["MagnetHoles"] == True:
                continue

            magnetDiameter = props.magnetDiameter
            magnetHeight = props.magnetHeight

            #Flip normals and Get bottom faces
            utils.selectBottomFaces(zobj)

            #get the lowest zValue of one the faces
            zValue = 0

            # Switch to Edit Mode
            bpy.ops.object.mode_set(mode='EDIT')
            mesh = bmesh.from_edit_mesh(zobj.data)

            # Get the world matrix to convert local to global coordinates
            world_matrix = zobj.matrix_world

            # Collect global Z-values of selected faces
            z_values = [
                (world_matrix @ face.calc_center_median()).z
                for face in mesh.faces if face.select
            ]
            
            zValue = min(z_values)


            bpy.ops.object.mode_set(mode='OBJECT')


            #Set 3D cursor to object's origin
            bpy.context.scene.cursor.location = zobj.location

            #Create 4 cylinders around the object
            radius = obj_size / 3
            angle_step = math.radians(90)
            created_cylinders = []

            for i in range(4):
                angle = i * angle_step
                offset_x = math.cos(angle) * radius
                offset_y = math.sin(angle) * radius
                pos = zobj.location + Vector((offset_x, offset_y, zValue))
                pos = zobj.location + Vector((offset_x, offset_y, 0))

                bpy.ops.mesh.primitive_cylinder_add(
                    radius=magnetDiameter / 2,
                    depth=magnetHeight*2,
                    location=pos
                )
                cyl = bpy.context.active_object
                created_cylinders.append(cyl)

            #Merge cylinders into one object
            bpy.ops.object.select_all(action='DESELECT')
            for cyl in created_cylinders:
                cyl.select_set(True)
            bpy.context.view_layer.objects.active = created_cylinders[0]
            bpy.ops.object.join()
            merged_cylinders = bpy.context.active_object

            #Perform boolean difference
            bpy.ops.object.select_all(action='DESELECT')
            zobj.select_set(True)
            bpy.context.view_layer.objects.active = zobj

            bool_mod = zobj.modifiers.new(name="MagnetCutout", type='BOOLEAN')
            bool_mod.operation = 'DIFFERENCE'
            bool_mod.object = merged_cylinders

            bpy.ops.object.modifier_apply(modifier=bool_mod.name)

            #Cleanup - delete the merged cutter object
            bpy.data.objects.remove(merged_cylinders, do_unlink=True)

            zobj["MagnetHoles"] = True

            bpy.ops.object.select_all(action='DESELECT')
            zobj.select_set(False)


        bpy.context.view_layer.objects.active = selected_objects[0]
        for zobj in selected_objects:
            zobj.select_set(True)
        

        print("Magnet holes Added")


        return{'FINISHED'}

class TP3D_OT_dovetail(bpy.types.Operator):
    bl_idname = "tp3d.dovetail"
    bl_label = "Dovetail"
    bl_options = {'REGISTER', 'UNDO'}
    
    def execute(self,context):

        selected_objects = context.selected_objects

        if not selected_objects:
            utils.show_message_box("No objects selected")
            return{'FINISHED'}
        
        bpy.ops.object.select_all(action='DESELECT')
        for zobj in selected_objects:
            zobj.select_set(False)
        
        for zobj in selected_objects:

            if zobj.type != 'MESH':
                continue

            if "Dovetail" not in zobj.keys():
                continue

            if zobj["Dovetail"] == True:
                continue

            zobj.select_set(True)
            bpy.context.view_layer.objects.active = zobj


            #Check for selection and custom property
            if zobj:
                if "objSize" not in zobj.keys():
                    break
            
            obj_size = zobj["objSize"]
            shapeRotation = zobj["shapeRotation"]
            dovetailSize = 15
            dovetailHeight = 3


            if obj_size <= 50:
                dovetailSize = 5
            elif obj_size <= 75:
                dovetailSize = 10

            #Flip normals and Get bottom faces
            utils.selectBottomFaces(zobj)

            # Switch to Edit Mode
            #bpy.ops.object.mode_set(mode='EDIT')
            mesh = bmesh.from_edit_mesh(zobj.data)

            bpy.ops.object.mode_set(mode='OBJECT')

            #Set 3D cursor to object's origin
            bpy.context.scene.cursor.location = zobj.location

            #Create cylinders around the object
            obj_shape = zobj.get("Shape", "HEXAGON")
            created_cylinders = []

            if obj_shape == "SQUARE":
                radius = obj_size/2 - dovetailSize/2
                angle_step = math.radians(90)
                steps = 4
                angle_start = math.radians(shapeRotation)
            else:  # HEXAGON
                radius = obj_size/2 * 0.866 - dovetailSize/2
                angle_step = math.radians(60)
                steps = 6
                angle_start = math.radians(shapeRotation) + math.radians(30)

            for i in range(steps):
                angle = i * angle_step + angle_start
                offset_x = math.cos(angle) * radius
                offset_y = math.sin(angle) * radius
                pos = zobj.location + Vector((offset_x, offset_y, 0 + dovetailHeight/2))
                rotation = Euler((0, 0, angle - math.radians(90)), 'XYZ')

                bpy.ops.mesh.primitive_cylinder_add(
                    vertices = 3,
                    radius=dovetailSize,
                    depth=dovetailHeight,
                    location=pos,
                    rotation = rotation
                )
                cyl = bpy.context.active_object
                created_cylinders.append(cyl)
        
            #Merge cylinders into one object
            bpy.ops.object.select_all(action='DESELECT')
            for cyl in created_cylinders:
                cyl.select_set(True)
            bpy.context.view_layer.objects.active = created_cylinders[0]
            bpy.ops.object.join()
            merged_cylinders = bpy.context.active_object

            #Select top faces of the Triangles to scale them up slightly
            utils.selectTopFaces(merged_cylinders)

            mesh = bmesh.from_edit_mesh(merged_cylinders.data)
            # Scale factor
            scale_factor = 1.05

            # Scale each selected face from its own center
            for face in mesh.faces:
                if face.select:
                    center = face.calc_center_median()
                    for vert in face.verts:
                        direction = vert.co - center
                        vert.co = center + direction * scale_factor

            # Update the mesh
            bmesh.update_edit_mesh(merged_cylinders.data, loop_triangles=False)

            bpy.ops.object.mode_set(mode='OBJECT')

            #Perform boolean difference
            bpy.ops.object.select_all(action='DESELECT')
            zobj.select_set(True)
            bpy.context.view_layer.objects.active = zobj

            bool_mod = zobj.modifiers.new(name="DovetailCutout", type='BOOLEAN')
            bool_mod.operation = 'DIFFERENCE'
            bool_mod.object = merged_cylinders
            

            zobj["Dovetail"] = True

            bpy.ops.object.modifier_apply(modifier=bool_mod.name)

            #Cleanup - delete the merged cutter object
            bpy.data.objects.remove(merged_cylinders, do_unlink=True)

            bpy.ops.object.select_all(action='DESELECT')
            zobj.select_set(False)
        
        bpy.context.view_layer.objects.active = selected_objects[0]
        for zobj in selected_objects:
            zobj.select_set(True)


        print("Dovetail Added")


        return{"FINISHED"}

class TP3D_OT_bottom_mark(bpy.types.Operator):
    bl_idname = "tp3d.bottom_mark"
    bl_label = "Bottom Mark"
    bl_options = {'REGISTER', 'UNDO'}

    def execute(self,context):

        selected_objects = context.selected_objects

        bottomMarkCutout = context.scene.tp3d.bottomMarkCutout

        if not selected_objects:
            utils.show_message_box("No objects selected")
            return{'FINISHED'}
        
        bpy.ops.object.select_all(action='DESELECT')
        for zobj in selected_objects:
            zobj.select_set(False)

        generated = False
        for zobj in selected_objects:
        
            #Check for selection and custom property
            if "BottomMark" not in zobj.keys():
                continue

            if zobj["BottomMark"] == True:
                continue

            if zobj.type == "MESH" and "objSize" in zobj:

                zobj.select_set(True)
                bpy.context.view_layer.objects.active = zobj

                mark = utils.BottomText(zobj)
                generated = True

                if bottomMarkCutout == True:

                    mark.scale.z = 2

                    utils.recalculateNormals(mark)
                    # Add boolean modifier
                    bool_mod = zobj.modifiers.new(name="Boolean", type='BOOLEAN')
                    bool_mod.object = mark
                    bool_mod.operation = 'DIFFERENCE'
                    bool_mod.solver = 'EXACT'

                    bpy.context.view_layer.objects.active = zobj
                    bpy.ops.object.modifier_apply(modifier=bool_mod.name)

                    bpy.data.objects.remove(mark, do_unlink=True)



                bpy.ops.object.select_all(action='DESELECT')
                zobj.select_set(False)



        
        if generated == False:
            utils.show_message_box("Not a valid Object selected")

        bpy.context.view_layer.objects.active = selected_objects[0]
        for zobj in selected_objects:
            zobj.select_set(True)



        return{'FINISHED'}

class TP3D_OT_terrain_dummy(bpy.types.Operator):
    bl_idname = "tp3d.terrain_dummy"
    bl_label = "Dummy Operator"
    def execute(self,context):
        self.report({'INFO'}, "This Feature is Exclusive for Patreon Supporters")
        return{"FINISHED"}


class TP3D_OT_color_mountain(bpy.types.Operator):
    bl_idname = "tp3d.color_mountain"
    bl_label = "Color Mountains"
    bl_description = "Color Mountains above a certain Threshold"
    bl_options = {'REGISTER', 'UNDO'}

    def execute(self,context):

        
        selected_objects = bpy.context.selected_objects
        min_treshold = context.scene.tp3d.mountain_treshold

        #Collect min/max from custom properties
        min_z = None
        max_z = None
        minThickness = None

        if not selected_objects:
            utils.show_message_box("No Object Selected. Please select a Map first")
            return {'CANCELLED'}

        for obj in selected_objects:
            if "lowestZ" in obj.keys() and "highestZ" in obj.keys() and obj["highestZ"] != 0:
                low = obj["lowestZ"]
                high = obj["highestZ"]
                minThickness = obj["minThickness"]
                min_z = low if min_z is None else min(min_z, low)
                max_z = high if max_z is None else max(max_z, high)

        #print(f"Lowest Z across objects: {min_z}, Highest Z: {max_z}")

        if min_z is None or max_z is None:
            utils.show_message_box("No valid Map object selected. Please select a generated Map first.", "INFO", "INFO")
            return {'CANCELLED'}

        #tres = (max_z-min_z)/100 * min_treshold + minThickness
        tres = (max_z + minThickness)/100 * min_treshold + 0.2# + minThickness
    

        #---------------------------------------
        #Create or get green material
       
        #Create or get a gray material
        mat = bpy.data.materials.get("MOUNTAIN")
        

        #Iterate objects and faces
        for obj in selected_objects:
            if obj.type != 'MESH' or obj["Object type"] != "MAP" or max_z == 0:
                print("Not Applied")
                continue
            if "lastMountianCut" in obj.keys():
                if obj["lastMountianCut"] == tres:
                    utils.show_message_box("Already Applied mountains at this height")
                    return{'FINISHED'}
                
            print("Apply Mountain Color")

            #obj.data.materials.clear()
            #obj.data.materials.append(matG)  # creates first slot and assigns

            def cut_mesh_at_height(obj, z_height):
                bpy.context.view_layer.objects.active = obj
                bpy.ops.object.mode_set(mode='EDIT')

                bmesh.update_edit_mesh(obj.data)
                bpy.ops.object.mode_set(mode='OBJECT')
                

            def color_mountains(obj, z_threshold, base_mat, mountain_mat):
                mesh = obj.data
                base_index = mesh.materials.find(base_mat)
                mount_index = mesh.materials.find(mountain_mat)
                print(f"t_treshold: {z_threshold}")
                for f in mesh.polygons:
                    if f.material_index not in (base_index, mount_index):
                        continue  # leave non-BASE/MOUNTAIN faces untouched
                    avg_z = sum(mesh.vertices[v].co.z for v in f.vertices) / len(f.vertices)
                    if avg_z > z_threshold:
                        f.material_index = mount_index
                    else:
                        f.material_index = base_index
                        

            obj = bpy.context.view_layer.objects.active

            #Ensure MOUNTAIN material exists on the object before coloring
            mat_index = obj.data.materials.find("MOUNTAIN")
            if mat_index == -1 and mat is not None:
                obj.data.materials.append(mat)
                mat_index = len(obj.data.materials) - 1

            cut_mesh_at_height(obj, tres)
            color_mountains(obj,tres,"BASE","MOUNTAIN")
            obj["lastMountianCut"] = tres
            


            #utils.merge_by_distance(obj, distance=0.001)

        return {'FINISHED'}

class TP3D_OT_contour_lines(bpy.types.Operator):
    bl_idname = "tp3d.contour_lines"
    bl_label = _("Contour Lines")
    bl_description = "Generate contour lines on the map"
    bl_options = {'REGISTER', 'UNDO'}

    def execute(self,context):


        selected_objects = bpy.context.selected_objects

        utils.contourLines(selected_objects)
        #utils.exaggeratedLayers(selected_objects)
            

        return {'FINISHED'}
    
class TP3D_OT_popup_merge(bpy.types.Operator):
    bl_idname = "tp3d.popup_merge"
    bl_label = "Merge Object with Map"
    bl_options = {'REGISTER', 'UNDO'}

    operation: bpy.props.EnumProperty(
        name="Type",
        items=[
            ("paint", "Paint on Surface", ""),
            ("separate", "Separate Object", ""),
            ("singleColorMode","Single-Color-Mode (Wireframe)",""),
            ("singleColorMode_remesh","Single-Color-Mode (Remesh)",""),
            ("negative","Negative",""),
        ],
        default="paint",
    ) # type: ignore

    xOffset: bpy.props.FloatProperty(name="X Offset", default=0) # type: ignore
    yOffset: bpy.props.FloatProperty(name="Y Offset", default=0) # type: ignore
    scaleFac: bpy.props.FloatProperty(name="Scale", default=1) # type: ignore
    rotation: bpy.props.FloatProperty(name="Rotation", default=0) # type: ignore

    # Internal variables to track state
    _start_location = None
    _start_rotation = None
    _start_scale = None
    orig_rotation = None
    orig_location = None
    orig_distance = None
    orig_perspective = None

    def check(self, context):
        obj = context.active_object

        # Apply transforms
        obj.location.x = self._start_location.x + self.xOffset
        obj.location.y = self._start_location.y + self.yOffset
        obj.rotation_euler.z = self._start_rotation + math.radians(self.rotation)
        obj.scale.x = obj.scale.y = self._start_scale * self.scaleFac

        
        return True

    def execute(self, context):

        obj = context.active_object
        if not obj: return {'CANCELLED'}

        # Convert to Mesh and Extrude
        bpy.ops.object.convert(target='MESH')
        bpy.ops.object.transform_apply(location=False, rotation=True, scale=True)
        
        #bpy.ops.object.mode_set(mode='EDIT')
        #bpy.ops.mesh.select_all(action='SELECT')
        # Simplified Extrude
        #bpy.ops.mesh.extrude_region_move(TRANSFORM_OT_translate={"value":(0, 0, 30)})
        #bpy.ops.object.mode_set(mode='OBJECT')
        obj.location.z = -1

        # Your custom projection logic
        Mapobject = context.scene.tp3d.currentMap
        utils.projection(self.operation, Mapobject, obj)

        # Restore View
        self.restore_view(context)
        return {'FINISHED'}

    def cancel(self, context):
        # Clean up the text object if user cancels
        if context.active_object:
            bpy.data.objects.remove(context.active_object, do_unlink=True)
        self.restore_view(context)
        return {'CANCELLED'}

    def restore_view(self, context):
        area = next(a for a in context.screen.areas if a.type == 'VIEW_3D')
        rv3d = area.spaces.active.region_3d
        rv3d.view_rotation = self.orig_rotation
        rv3d.view_location = self.orig_location
        rv3d.view_distance = self.orig_distance
        if self.orig_perspective is not None:
            rv3d.view_perspective = self.orig_perspective

    def invoke(self, context, event):
        # Create the object

        obj = bpy.context.view_layer.objects.active
        context.scene.cursor.location = obj.location.copy()



        self._start_location = obj.location.copy()
        self._start_rotation = obj.rotation_euler.z
        self._start_scale = obj.scale.x


        # Store View State
        area = next(a for a in context.screen.areas if a.type == 'VIEW_3D')
        rv3d = area.spaces.active.region_3d
        self.orig_rotation = rv3d.view_rotation.copy()
        self.orig_location = rv3d.view_location.copy()
        self.orig_distance = rv3d.view_distance
        self.orig_perspective = rv3d.view_perspective

        utils.zoom_camera_to_selected(context.scene.tp3d.currentMap)
        # Setup Camera view
        rv3d.view_rotation = Quaternion((1, 0, 0, 0))
        rv3d.view_location = obj.location.copy()
        rv3d.view_perspective = 'ORTHO'

        # Group this initial creation with the rest of the operator for UNDO
        bpy.ops.ed.undo_push(message="Add Text Popup")

        return context.window_manager.invoke_props_dialog(self)

class TP3D_OT_import_text(bpy.types.Operator):
    bl_idname = "tp3d.import_text"
    bl_label = "Import Text"
    bl_description = "Import Text to place it on your Map"
    bl_options = {'REGISTER', 'UNDO'}

    def execute(self,context):
        
        obj = bpy.context.view_layer.objects.active
        if obj == None:
            utils.show_message_box("No Map Selected")
            return {'FINISHED'}

        if "objSize" not in obj.keys():
            utils.show_message_box("Selected object is not a Map")
            return {'FINISHED'}

        bpy.ops.tp3d.popup_text('INVOKE_DEFAULT')
        return {'FINISHED'}

class TP3D_OT_popup_text(bpy.types.Operator):
    bl_idname = "tp3d.popup_text"
    bl_label = "Import Text"
    bl_options = {'REGISTER', 'UNDO'}

    def on_font_change(self, context):
        # Run your font loading logic here
        obj = context.active_object

        if self.textFont:
            clean_path = bpy.path.abspath(self.textFont)
            if os.path.exists(clean_path):
                try:
                    # Only load if it's not already the current font
                    font_name = os.path.basename(clean_path)
                    if font_name in bpy.data.fonts:
                        new_fnt = bpy.data.fonts[font_name]
                    else:
                        new_fnt = bpy.data.fonts.load(clean_path)
                    
                    if obj.data.font != new_fnt:
                        obj.data.font = new_fnt
                except Exception as e:
                    print(f"Font Load Error: {e}")

    text: StringProperty(name="Name", default="Text") # type: ignore
    textFont: StringProperty(
        name="Font",
        description="Select a .ttf or .otf file",
        default="",
        subtype='FILE_PATH',
        update=on_font_change
    ) # type: ignore
    xOffset: bpy.props.FloatProperty(name="X Offset", default=0) # type: ignore
    yOffset: bpy.props.FloatProperty(name="Y Offset", default=0) # type: ignore
    scaleFac: bpy.props.FloatProperty(name="Scale", default=1) # type: ignore
    rotation: bpy.props.FloatProperty(name="Rotation", default=0) # type: ignore

    bottomSide: bpy.props.BoolProperty(name="Bottom Side", default = False) # type: ignore

    operation: bpy.props.EnumProperty(
        name="Type",
        items=[
            ("paint", "Paint on Surface", ""),
            ("separate", "Separate Object", ""),
            ("singleColorMode","Single-Color-Mode (Wireframe)",""),
            ("singleColorMode_remesh","Single-Color-Mode (Remesh)",""),
            ("negative","Negative",""),
        ],
        default="paint",
    ) # type: ignore

    # Internal variables to track state
    _start_location = None
    _start_rotation = None
    _start_scale = None
    orig_rotation = None
    orig_location = None
    orig_distance = None
    orig_perspective = None

    topZ = 0
    bottomZ = 0

    rv3d = None

    def draw(self, context):
        layout = self.layout

        layout.prop(self, "text")
        layout.prop(self, "textFont")
        layout.prop(self, "xOffset")
        layout.prop(self, "yOffset")
        layout.prop(self, "scaleFac")
        layout.prop(self, "rotation")
        layout.prop(self, "bottomSide")
        if self.bottomSide == False:
            layout.prop(self, "operation")

    def check(self, context):
        obj = context.active_object

        multi = 1
        if self.bottomSide == True:
            multi = -1

        # Apply transforms
        obj.location.x = self._start_location.x + self.xOffset * multi
        obj.location.y = self._start_location.y + self.yOffset
        obj.rotation_euler.z = self._start_rotation + math.radians(self.rotation)
        obj.scale.x = self._start_scale * self.scaleFac * multi
        obj.scale.y = self._start_scale * self.scaleFac

        # Update Text Body
        obj.data.body = self.text

        if self.bottomSide == True and self.rv3d.view_rotation == Quaternion((1, 0, 0, 0)):
            self.rv3d.view_rotation = Quaternion((0,0,1,0))
            obj.location.z  = self.bottomZ
        
        if self.bottomSide == False and self.rv3d.view_rotation == Quaternion((0,0,1,0)):
            self.rv3d.view_rotation = Quaternion((1,0,0,0))
            obj.location.z  = self.topZ
        
        return True

    def execute(self, context):

        obj = context.active_object
        if not obj: return {'CANCELLED'}

        # Save last used font to scene props
        if self.textFont:
            context.scene.tp3d.textFont = self.textFont

        # Convert to Mesh and Extrude
        bpy.ops.object.convert(target='MESH')
        bpy.ops.object.transform_apply(location=False, rotation=True, scale=True)

        #bpy.ops.object.mode_set(mode='EDIT')
        #bpy.ops.mesh.select_all(action='SELECT')
        # Simplified Extrude
        #bpy.ops.mesh.extrude_region_move(TRANSFORM_OT_translate={"value":(0, 0, 30)})
        #bpy.ops.object.mode_set(mode='OBJECT')

        # Your custom projection logic
        Mapobject = context.scene.tp3d.currentMap

        

        if self.bottomSide == False:
            obj.location.z = -1
            utils.projection(self.operation, Mapobject, obj)
        else:
            obj.location.z = Mapobject.location.z

            bpy.ops.object.select_all(action="DESELECT")

            if obj.type == "FONT":
                obj.select_set(True)
                bpy.context.view_layer.objects.active = obj
                bpy.ops.object.convert(target='MESH')

            bpy.ops.object.mode_set(mode='EDIT')
            bpy.ops.mesh.select_all(action='SELECT')
            bpy.ops.mesh.extrude_region_move()
            bpy.ops.transform.translate(value=(0, 0, 0.4))#bpy.ops.mesh.select_all(action='DESELECT')
            bpy.ops.object.mode_set(mode='OBJECT')
                
            utils.intersectWithTile(Mapobject,obj)

            utils.boolean_operation(Mapobject,obj)


        # Restore View
        self.restore_view(context)
        return {'FINISHED'}

    def cancel(self, context):
        # Clean up the text object if user cancels
        if context.active_object:
            bpy.data.objects.remove(context.active_object, do_unlink=True)
        self.restore_view(context)

        bpy.ops.object.select_all(action="DESELECT")
        obj = context.scene.tp3d.currentMap
        obj.select_set(True)
        bpy.context.view_layer.objects.active = obj

        return {'CANCELLED'}

    def restore_view(self, context):
        area = next(a for a in context.screen.areas if a.type == 'VIEW_3D')
        self.rv3d = area.spaces.active.region_3d
        self.rv3d.view_rotation = self.orig_rotation
        self.rv3d.view_location = self.orig_location
        self.rv3d.view_distance = self.orig_distance
        if self.orig_perspective is not None:
            self.rv3d.view_perspective = self.orig_perspective

    def invoke(self, context, event):
        # Create the object

        map = bpy.context.view_layer.objects.active
        context.scene.tp3d.currentMap = map
        context.scene.cursor.location = map.location.copy()



        bpy.ops.object.text_add(location=context.scene.cursor.location)
        obj = context.active_object



        if "highestZ" in map.keys() and 1 == 0:

            self.topZ = map["highestZ"] + map["minThickness"] + 0.5 + map.location.z
            self.bottomZ = map.location.z - 0.5
        else:
            bot, top = utils.getHighestLowest(map)
            print(f"Highest point: {top}")

            self.bottomZ = bot - 0.2
            self.topZ = top + 0.2

        obj.location.z = self.topZ
        
        # Initial Setup
        obj.data.align_x = 'CENTER'
        obj.data.align_y = 'CENTER'
        obj.data.size = 20
        
        self._start_location = obj.location.copy()
        self._start_rotation = obj.rotation_euler.z
        self._start_scale = 1.0

        # Store View State
        area = next(a for a in context.screen.areas if a.type == 'VIEW_3D')
        self.rv3d = area.spaces.active.region_3d
        self.orig_rotation = self.rv3d.view_rotation.copy()
        self.orig_location = self.rv3d.view_location.copy()
        self.orig_distance = self.rv3d.view_distance
        self.orig_perspective = self.rv3d.view_perspective

        utils.zoom_camera_to_selected(map)

        # Setup Camera view
        self.rv3d.view_rotation = Quaternion((1, 0, 0, 0))
        self.rv3d.view_location = obj.location.copy()
        self.rv3d.view_distance = map["objSize"] * 1.6
        self.rv3d.view_perspective = 'ORTHO'

        # Restore last used font
        if context.scene.tp3d.textFont:
            self.textFont = context.scene.tp3d.textFont

        # Group this initial creation with the rest of the operator for UNDO
        bpy.ops.ed.undo_push(message="Add Text Popup")

        return context.window_manager.invoke_props_dialog(self)

class TP3D_OT_import_svg(bpy.types.Operator):
    bl_idname = "tp3d.import_svg"
    bl_label = "Import SVG"
    bl_description = "Import an SVG file onto the map"
    bl_options = {'REGISTER', 'UNDO'}

    def execute(self,context):
        
        obj = bpy.context.view_layer.objects.active
        if obj == None:
            utils.show_message_box("No Map Selected")
            return {'FINISHED'}

        if "objSize" not in obj.keys():
            utils.show_message_box("Selected object is not a Map")
            return {'FINISHED'}

        bpy.ops.tp3d.popup_svg('INVOKE_DEFAULT')
        return {'FINISHED'}
    
class TP3D_OT_popup_svg(bpy.types.Operator):
    bl_idname = "tp3d.popup_svg"
    bl_label = "Import SVG"
    bl_options = {'REGISTER', 'UNDO'}

    xOffset: bpy.props.FloatProperty(name= _("X Offset"), default = 0) # type: ignore
    yOffset: bpy.props.FloatProperty(name= _("Y Offset"), default = 0) # type: ignore
    scaleFac: bpy.props.FloatProperty(name= _("Scale"), default = 1) # type: ignore
    rotation: bpy.props.FloatProperty(name= _("Rotation"), default = 0) # type: ignore

    bottomSide: bpy.props.BoolProperty(name="Bottom Side", default = False) # type: ignore

    operation: bpy.props.EnumProperty(
        name="Type",
        description= _("Choose how the SVG should be used"),
        items=[
            ("paint", "Paint on Surface", "Paints the SVG onto the surface"),
            ("separate", "Separate Object", "SVG as Separate Object"),
            ("singleColorMode","Single-Color-Mode (Wireframe)","Creates the SVG as a object you can print separately"),
            ("singleColorMode_remesh","Single-Color-Mode (Remesh)","Creates the SVG as a separate object using the remesh-based algorithm"),
            ("negative","Negative","Adds the SVG as a negative space"),
        ],
        default = "paint",
        
    )# type: ignore
    

    _start_location = None
    _start_scale = None
    _start_rotation = None

    orig_rotation = None
    orig_location = None
    orig_distance = None
    orig_perspective = None

    topZ = 0
    bottomZ = 0

    rv3d = None

    def draw(self, context):
        layout = self.layout

        layout.prop(self, "xOffset")
        layout.prop(self, "yOffset")
        layout.prop(self, "scaleFac")
        layout.prop(self, "rotation")
        layout.prop(self, "bottomSide")
        if self.bottomSide == False:
            layout.prop(self, "operation")

    def check(self, context):
        obj = context.active_object
        if not obj:
            return False

        if self._start_location is None:
            return False
        if self._start_rotation is None:
            return False
        if self._start_scale is None:
            return False
        
        multi = 1
        if self.bottomSide == True:
            multi = -1

        # Apply transforms
        obj.location.x = self._start_location.x + self.xOffset * multi
        obj.location.y = self._start_location.y + self.yOffset
        obj.rotation_euler.z = self._start_rotation + math.radians(self.rotation)
        obj.scale.x = self._start_scale * self.scaleFac * multi
        obj.scale.y = self._start_scale * self.scaleFac

        if self.bottomSide == True and self.rv3d.view_rotation == Quaternion((1, 0, 0, 0)):
            self.rv3d.view_rotation = Quaternion((0,0,1,0))
            obj.location.z  = self.bottomZ
        
        if self.bottomSide == False and self.rv3d.view_rotation == Quaternion((0,0,1,0)):
            self.rv3d.view_rotation = Quaternion((1,0,0,0))
            obj.location.z  = self.topZ


        return True  # Redraw UI

    def execute(self,context):

        Mapobject = context.scene.tp3d.currentMap
        obj = bpy.context.view_layer.objects.active

        obj.scale.z = 20


        utils.recalculateNormals(Mapobject)
        utils.recalculateNormals(obj)


        if self.bottomSide == False:
            obj.location.z = -1
            utils.projection(self.operation, Mapobject, obj)
        else:

            obj.location.z = Mapobject.location.z
            obj.scale.z = 0.8

            bpy.ops.object.select_all(action="DESELECT")
            obj.select_set(True)
            bpy.context.view_layer.objects.active = obj

            bpy.ops.object.transform_apply(location=False, rotation=True, scale=True)
                
            utils.intersectWithTile(Mapobject,obj)
            obj.location.z -= 0.4
            utils.recalculateNormals(obj)

            utils.boolean_operation(Mapobject,obj)
            obj.location.z += 0.4
            obj.scale.z *= 0.5

        self.rv3d.view_rotation = self.orig_rotation
        self.rv3d.view_location = self.orig_location
        self.rv3d.view_distance = self.orig_distance
        if self.orig_perspective is not None:
            self.rv3d.view_perspective = self.orig_perspective

        return {'FINISHED'}

    def cancel(self,context):

        obj = bpy.context.view_layer.objects.active

        utils.remove_objects(obj)

        self.rv3d.view_rotation = self.orig_rotation
        self.rv3d.view_location = self.orig_location
        self.rv3d.view_distance = self.orig_distance
        if self.orig_perspective is not None:
            self.rv3d.view_perspective = self.orig_perspective

        bpy.ops.object.select_all(action="DESELECT")
        obj = context.scene.tp3d.currentMap
        obj.select_set(True)
        bpy.context.view_layer.objects.active = obj

        return {'CANCELLED'}

    def invoke(self,context,event):

        map = bpy.context.view_layer.objects.active
        bpy.context.scene.cursor.location = map.location.copy()

        context.scene.tp3d.currentMap = map
        
        svg = utils.importSVGtoMerge(map)

        svg.data.materials.clear()

        if svg == None:
            self.report({'WARNING'}, "No Valid object selected")
            utils.show_message_box("No valid Map selected")
            return {'CANCELLED'}

        obj = context.active_object
        if not obj or obj == 0:
            self.report({'WARNING'}, "No object selected")
            return {'CANCELLED'}
        
        if "highestZ" in map.keys():

            self.topZ = map["highestZ"] + map["minThickness"] + 0.5 + map.location.z
            self.bottomZ = map.location.z - 0.5
        else:
            bot, top = utils.getHighestLowest(map)

            self.bottomZ = bot - 0.2
            self.topZ = top + 0.2
            
        obj.location.z = self.topZ
    
        # Define Startposition of the selected object
        self._start_location = obj.location.copy()
        self._start_rotation = obj.rotation_euler.z
        self._start_scale = 1

        area = next(a for a in bpy.context.screen.areas if a.type == 'VIEW_3D')
        space = area.spaces.active
        self.rv3d = space.region_3d

        self.orig_rotation = self.rv3d.view_rotation.copy()
        self.orig_location = self.rv3d.view_location.copy()
        self.orig_distance = self.rv3d.view_distance
        self.orig_perspective = self.rv3d.view_perspective

        utils.zoom_camera_to_selected(map)

        cursor_loc = bpy.context.scene.cursor.location
        self.rv3d.view_location = cursor_loc.copy()

        self.rv3d.view_rotation = Quaternion((1, 0, 0, 0))  # identity = top view
        self.rv3d.view_distance = map["objSize"] * 1.6
        self.rv3d.view_perspective = 'ORTHO'

        return context.window_manager.invoke_props_dialog(self)

class TP3D_OT_import_pin(bpy.types.Operator):
    bl_idname = "tp3d.import_pin"
    bl_label = "Import Pin"
    bl_description = "Place a Pin on your Map interactively"
    bl_options = {'REGISTER', 'UNDO'}

    def execute(self, context):
        obj = bpy.context.view_layer.objects.active
        if obj is None:
            utils.show_message_box("No Map Selected")
            return {'FINISHED'}

        if "objSize" not in obj.keys():
            utils.show_message_box("Selected object is not a Map")
            return {'FINISHED'}

        bpy.ops.tp3d.popup_pin('INVOKE_DEFAULT')
        return {'FINISHED'}


class TP3D_OT_popup_pin(bpy.types.Operator):
    bl_idname = "tp3d.popup_pin"
    bl_label = "Place Pin"
    bl_options = {'REGISTER', 'UNDO'}

    xOffset: bpy.props.FloatProperty(name="X Offset", default=0) # type: ignore
    yOffset: bpy.props.FloatProperty(name="Y Offset", default=0) # type: ignore
    scaleFac: bpy.props.FloatProperty(name="Scale", default=1) # type: ignore

    _start_location = None
    _start_scale = None

    orig_rotation = None
    orig_location = None
    orig_distance = None
    orig_perspective = None

    topZ = 0

    rv3d = None

    def draw(self, context):
        layout = self.layout
        layout.prop(self, "xOffset")
        layout.prop(self, "yOffset")
        layout.prop(self, "scaleFac")

    def check(self, context):
        obj = context.active_object
        if not obj:
            return False
        if self._start_location is None or self._start_scale is None:
            return False

        obj.location.x = self._start_location.x + self.xOffset
        obj.location.y = self._start_location.y + self.yOffset
        obj.scale.x = self._start_scale * self.scaleFac
        obj.scale.y = self._start_scale * self.scaleFac
        obj.scale.z = self._start_scale * self.scaleFac

        # Snap Z to terrain surface via raycast
        map_obj = context.scene.tp3d.currentMap
        if map_obj:
            hit_z = utils.RaycastPointToMeshZ((obj.location.x, obj.location.y, 0), map_obj)
            if hit_z is not None:
                obj.location.z = hit_z + 2 * self.scaleFac - 1  # 1mm embedded into surface

        return True

    def execute(self, context):
        obj = bpy.context.view_layer.objects.active
        if not obj:
            return {'CANCELLED'}

        # Final raycast snap to terrain surface
        map_obj = context.scene.tp3d.currentMap
        if map_obj:
            hit_z = utils.RaycastPointToMeshZ((obj.location.x, obj.location.y, 0), map_obj)
            if hit_z is not None:
                obj.location.z = hit_z + 2 * self.scaleFac - 1
            else:
                obj.location.z = self.topZ + 1
        else:
            obj.location.z = self.topZ + 1

        self.rv3d.view_rotation = self.orig_rotation
        self.rv3d.view_location = self.orig_location
        self.rv3d.view_distance = self.orig_distance
        if self.orig_perspective is not None:
            self.rv3d.view_perspective = self.orig_perspective

        return {'FINISHED'}

    def cancel(self, context):
        obj = bpy.context.view_layer.objects.active
        if obj:
            bpy.data.objects.remove(obj, do_unlink=True)

        self.rv3d.view_rotation = self.orig_rotation
        self.rv3d.view_location = self.orig_location
        self.rv3d.view_distance = self.orig_distance
        if self.orig_perspective is not None:
            self.rv3d.view_perspective = self.orig_perspective

        bpy.ops.object.select_all(action="DESELECT")
        map_obj = context.scene.tp3d.currentMap
        if map_obj:
            map_obj.select_set(True)
            bpy.context.view_layer.objects.active = map_obj

        return {'CANCELLED'}

    def invoke(self, context, event):
        map = bpy.context.view_layer.objects.active
        context.scene.cursor.location = map.location.copy()
        context.scene.tp3d.currentMap = map

        # Create cone pin at cursor location
        cursor_loc = context.scene.cursor.location
        bpy.ops.mesh.primitive_cone_add(
            vertices=16,
            radius1=0.4,
            radius2=0.8,
            depth=4,
            location=cursor_loc
        )
        obj = context.active_object
        if not obj:
            self.report({'WARNING'}, "Failed to create pin object")
            return {'CANCELLED'}
        obj.name = "Pin_Placement"
        mat = bpy.data.materials.get("TRAIL")
        if mat:
            obj.data.materials.append(mat)

        if "highestZ" in map.keys():
            self.topZ = map["highestZ"] + map["minThickness"] + 0.5 + map.location.z
        else:
            _bot, top = utils.getHighestLowest(map)
            self.topZ = top + 0.2

        obj.location.z = self.topZ + 2

        self._start_location = obj.location.copy()
        self._start_scale = 1.0

        area = next(a for a in bpy.context.screen.areas if a.type == 'VIEW_3D')
        space = area.spaces.active
        self.rv3d = space.region_3d

        self.orig_rotation = self.rv3d.view_rotation.copy()
        self.orig_location = self.rv3d.view_location.copy()
        self.orig_distance = self.rv3d.view_distance
        self.orig_perspective = self.rv3d.view_perspective

        utils.zoom_camera_to_selected(map)
        self.rv3d.view_rotation = Quaternion((1, 0, 0, 0))
        self.rv3d.view_location = obj.location.copy()
        self.rv3d.view_distance = map["objSize"] * 1.6
        self.rv3d.view_perspective = 'ORTHO'

        bpy.ops.ed.undo_push(message="Add Pin Popup")

        return context.window_manager.invoke_props_dialog(self)

class TP3D_OT_install_three_mf(bpy.types.Operator):
    bl_idname = "tp3d.install_three_mf"
    bl_label = "Install 3MF Extension"
    bl_description = "Automatically downloads and enables the 3MF extension by Clonephaze"

    def execute(self, context):
        pkg_idd = "ThreeMF_io"

        try:
            bpy.ops.extensions.repo_sync_all()
            bpy.ops.extensions.package_install(repo_index=0, pkg_id=pkg_idd)
            
        except Exception as e:
            print({'ERROR'}, f"Install failed: {e}")
            utils.show_message_box("Install failed: Online access may be disabled. Please enable it in Blender Preferences > System > Network.", "ERROR", "3MF Install Failed")

        inst=  utils.is_3mf_extension_installed()
        print(f"Inst {inst}")        
    
        return {'FINISHED'}