#  Copyright (C) 2026  EmGi

# You are free to modify it under the terms of the GNU General Public License as published by the Free Software Foundation.
# You are free to use any models Generated by this Addon Commercially

import bpy

from . import temp

from bpy.app.translations import pgettext_iface as _ #For Translation of Text Required


class TP3D_PT_generate(bpy.types.Panel):
    bl_label = "Create"
    bl_idname = "TP3D_PT_generate"
    bl_space_type = 'VIEW_3D'
    bl_region_type = 'UI'
    bl_category = "TrailPrint3D"
    bl_options = set()
    

    def draw(self, context):
        layout = self.layout
        props = context.scene.tp3d

        # --- Header ---
        row = layout.row(align=True)
        row.operator("tp3d.open_website", text=_("Patreon"), icon='FUND')
        row.operator("tp3d.join_discord", text=_("Discord"), icon='URL')
        edition = "Premium" if temp.PREMIUMVERSION else "Free"
        layout.label(text=_(f"Created by: EmGi  |  {edition} v3.08"), icon='INFO')
        layout.separator()

        # --- Generation mode toggle (3 columns) ---
        row = layout.row(align=True)
        if temp.PREMIUMVERSION:
            row.prop(props, "generation_mode", expand=True)
        else:
            row.prop_enum(props, "generation_mode", 'GENERATION')
            row.operator("tp3d.terrain_dummy", text=_("Multi"), icon='LOCKED')
            row.operator("tp3d.terrain_dummy", text=_("Terrain"), icon='LOCKED')

        # --- Generate button ---
        col = layout.column()
        col.scale_y = 1.4
        if props.generation_mode == 'GENERATION':
            col.operator("tp3d.run_generation", icon='DISC')
        elif props.generation_mode == 'MULTI':
            if temp.PREMIUMVERSION:
                col.operator("tp3d.chain_generation", icon="OUTLINER_DATA_CURVES")
            else:
                col.operator("tp3d.terrain_dummy", text=_("Multi Generation"), icon="LOCKED")
        else:  # TERRAIN
            if props.sScaleHor is not None and temp.PREMIUMVERSION:
                if props.mapmode == 'FROMCENTER':
                    col.operator("tp3d.from_center_generation", text=_("Generate (Center + Radius)"), icon='DISC')
                elif props.mapmode == 'FROMPLANE':
                    col.operator("tp3d.terrain", text=_("Generate from Blank"), icon="OBJECT_DATA")
                elif props.mapmode == '2POINTS':
                    col.operator("tp3d.2point_generation", text=_("Generate (2 Corner Points)"), icon='DISC')
            else:
                col.operator("tp3d.terrain_dummy", text=_("Generate Terrain"), icon="LOCKED")

        # --- Settings (collapsible) ---
        layout.prop(props, "show_create_settings",
                    icon="TRIA_DOWN" if props.show_create_settings else "TRIA_RIGHT", emboss=False)
        if props.show_create_settings:
            if props.generation_mode == 'TERRAIN':
                # Custom Map Generation
                box = layout.box()
                box.label(text=_("Custom Map Generation"), icon='MOD_BUILD')
                if props.sScaleHor is not None and temp.PREMIUMVERSION:
                    box.prop(props, "mapmode", text=_("Mode"))
                    boxer = box.box()
                    if props.mapmode == "FROMPLANE":
                        boxer.operator("tp3d.create_blank", text=_("Create Blank"), icon="SNAP_FACE")
                        boxer.operator("tp3d.extend_tile", text=_("Extend Selected Tile"), icon="SELECT_EXTEND")
                        boxer.prop(props, "tileSpacing")
                        boxer.prop(props, "indipendendTiles")
                    elif props.mapmode == "FROMCENTER":
                        row = boxer.row(align=True)
                        row.prop(props, "jMapLat")
                        row.prop(props, "jMapLon")
                        boxer.prop(props, "jMapRadius")
                    elif props.mapmode == "2POINTS":
                        row = boxer.row(align=True)
                        row.prop(props, "jMapLat1")
                        row.prop(props, "jMapLon1")
                        row = boxer.row(align=True)
                        row.prop(props, "jMapLat2")
                        row.prop(props, "jMapLon2")
                    box.separator(factor=0.5)
                    col = box.column(align=True)
                    col.operator("tp3d.merge_with_map", text=_("Merge with Map"), icon="AUTOMERGE_OFF")
                    col.operator("tp3d.generate_just_trail", text=_("Generate Just Trail"), icon="DECORATE_DRIVER")
                else:
                    col = box.column(align=True)
                    col.operator("tp3d.terrain_dummy", text=_("Create Map from selected"), icon="LOCKED")
                    col.operator("tp3d.terrain_dummy", text=_("Merge with Map"), icon="LOCKED")
                    col.operator("tp3d.terrain_dummy", text=_("Create Blank"), icon="LOCKED")
            else:
                # Files
                box = layout.box()
                box.label(text=_("Files"), icon='FILE_FOLDER')
                col = box.column(align=True)
                if props.generation_mode == 'GENERATION':
                    col.prop(props, "file_path")
                elif temp.PREMIUMVERSION:
                    col.prop(props, "chain_path")
                else:
                    col.label(text=_("Exclusive for Patreon Supporters"), icon='FUND')
                    col.label(text=_("- Chain together multiple Trails"))
                col.prop(props, "export_path")
                box.prop(props, "trailName")

            # Shape
            box = layout.box()
            box.label(text=_("Shape"), icon='MESH_DATA')
            col = box.column(align=True)
            col.prop(props, "shape")
            col.separator(factor=0.5)
            if props.shape == "SQUARE":
                row = col.row(align=True)
                row.prop(props, "objSize", text=_("Width"))
                row.prop(props, "rectangleHeight", text=_("Height"))
            elif props.shape == "ELLIPSE":
                col.prop(props, "objSize")
                col.prop(props, "ellipseRatio")
            else:
                col.prop(props, "objSize")
            col.prop(props, "num_subdivisions")

            # Trail & Elevation
            box = layout.box()
            box.label(text=_("Trail & Elevation"), icon='NORMALIZE_FCURVES')
            col = box.column(align=True)
            col.prop(props, "scaleElevation")
            col.prop(props, "pathThickness")
            col.prop(props, "singleColorMode")

            # Scale
            box = layout.box()
            box.label(text=_("Scale"), icon='DRIVER_DISTANCE')
            col = box.column(align=True)
            col.prop(props, "scalemode")
            if props.scalemode in {"FACTOR", "SCALE"}:
                col.prop(props, "pathScale")
            elif props.scalemode == "COORDINATES":
                row = col.row(align=True)
                row.prop(props, "scaleLat1")
                row.prop(props, "scaleLon1")
                row = col.row(align=True)
                row.prop(props, "scaleLat2")
                row.prop(props, "scaleLon2")

        # --- Status ---
        layout.separator(factor=0.5)
        layout.label(text=props.o_time, icon='TIME')

class TP3D_PT_advanced(bpy.types.Panel):
    bl_label = "Advanced"
    bl_idname = "TP3D_PT_advanced"
    bl_space_type = "VIEW_3D"
    bl_region_type = "UI"
    bl_category = "TrailPrint3D"
    
    def draw(self, context):
        layout = self.layout
        props = context.scene.tp3d

        # --- Export ---
        layout.prop(props, "show_export", icon="TRIA_DOWN" if props.show_export else "TRIA_RIGHT", emboss=False)
        if props.show_export:
            box = layout.box()
            row = box.row(align=True)
            if temp.has3mf and not props.disable_3mf_export:
                row.operator("tp3d.export_three_mf", text="3MF")
            row.operator("tp3d.export_obj", text="OBJ")
            row.operator("tp3d.export_stl", text="STL")
            if not temp.has3mf:
                box.operator("tp3d.install_three_mf", text=_("Install 3MF Addon"), icon='IMPORT')
            box.prop(props, "disable_auto_export")
            if temp.has3mf:
                box.prop(props, "disable_3mf_export")

        # --- MAP ---
        layout.prop(props, "show_map", icon="TRIA_DOWN" if props.show_map else "TRIA_RIGHT", emboss=False)
        if props.show_map:
            box = layout.box()
            col = box.column(align=True)
            col.prop(props, "minThickness")
            col.prop(props, "shapeRotation")
            row = col.row(align=True)
            row.prop(props, "xTerrainOffset", text=_("X-Offset"))
            row.prop(props, "yTerrainOffset", text=_("Y-Offset"))
            col.prop(props, "overwritePathElevation", text=_("Snap Trail to Terrain"))
            col.prop(props, "fixedElevationScale")

            tol_box = box.box()
            tol_box.label(text=_("Single-Color-mode Tolerances"), icon='SNAP_MIDPOINT')
            col = tol_box.column(align=True)
            col.prop(props, "tolerance")
            col.prop(props, "toleranceElements")

            box.separator(factor=0.5)

        # --- INCLUDE ELEMENTS ---
        layout.prop(props, "show_coloring", icon="TRIA_DOWN" if props.show_coloring else "TRIA_RIGHT", emboss=False)
        if props.show_coloring:
            box = layout.box()
            box.label(text=_("Terrain Elements"), icon='TEXTURE')
            box.prop(props, "elementMode")
            # if "SINGLECOLORMODE" in props.elementMode:
            #     box.prop(props, "elementModeInset")

            sub = box.box()
            row = sub.row()
            row.prop(props, "show_water", icon="TRIA_DOWN" if props.show_water else "TRIA_RIGHT", emboss=False, text=_("Water & Ocean"))
            _any_water = props.col_wPondsActive or props.col_wSmallRiversActive or props.col_wBigRiversActive or props.el_oActive
            row.label(text="", icon='CHECKBOX_HLT' if _any_water else 'CHECKBOX_DEHLT')
            if props.show_water:
                col = sub.column(align=True)
                row = col.row(align=True)
                row.prop(props, "col_wPondsActive", icon='CHECKBOX_HLT' if props.col_wPondsActive else 'CHECKBOX_DEHLT')
                row.prop(props, "col_wBigRiversActive", icon='CHECKBOX_HLT' if props.col_wBigRiversActive else 'CHECKBOX_DEHLT')
                row = col.row(align=True)
                row.prop(props, "col_wSmallRiversActive", icon='CHECKBOX_HLT' if props.col_wSmallRiversActive else 'CHECKBOX_DEHLT')
                row.prop(props, "col_wStreamWidth")
                col.prop(props, "col_wArea")
                row = col.row(align=True)
                row.prop(props, "el_oActive", icon='CHECKBOX_HLT' if props.el_oActive else 'CHECKBOX_DEHLT')
                row.prop(props, "el_oFlip", icon='CHECKBOX_HLT' if props.el_oFlip else 'CHECKBOX_DEHLT')

            sub = box.box()
            sub.label(text=_("Forests"), icon='FORCE_WIND')
            row = sub.row(align=True)
            row.prop(props, "col_fActive")
            row.prop(props, "col_fArea")

            sub = box.box()
            sub.label(text=_("Scree"), icon='RNDCURVE')
            row = sub.row(align=True)
            row.prop(props, "col_scrActive")
            row.prop(props, "col_scrArea")

            sub = box.box()
            sub.label(text=_("City Boundaries"), icon='HOME')
            row = sub.row(align=True)
            row.prop(props, "col_cActive")
            row.prop(props, "col_cArea")

            sub = box.box()
            sub.label(text=_("Greenspaces"), icon='OUTLINER_OB_POINTCLOUD')
            row = sub.row(align=True)
            row.prop(props, "col_grActive")
            row.prop(props, "col_grArea")

            sub = box.box()
            sub.label(text=_("Farmland"), icon='OUTLINER_OB_SURFACE')
            row = sub.row(align=True)
            row.prop(props, "col_faActive")
            row.prop(props, "col_faArea")

            sub = box.box()
            sub.label(text=_("Glaciers"), icon='FREEZE')
            row = sub.row(align=True)
            row.prop(props, "col_glActive")
            row.prop(props, "col_glArea")

            #layout.prop(props, "col_KeepManifold")

            box = layout.box()
            box.label(text=_("3D Elements (Experimental)"), icon='MESH_CUBE')
            box.label(text=_("Not compatible with singleColorMode"), icon='ERROR')

            sub = box.box()
            sub.label(text=_("Buildings"), icon='OUTLINER_OB_MESH')
            row = sub.row(align=True)
            row.prop(props, "el_bActive")
            row.prop(props, "el_bHeightMultiplier")

            sub = box.box()
            row = sub.row()
            row.prop(props, "show_roads", icon="TRIA_DOWN" if props.show_roads else "TRIA_RIGHT", emboss=False, text=_("Roads"))
            _any_road = props.el_sBigActive or props.el_sMedActive or props.el_sSmallActive
            row.label(text="", icon='CHECKBOX_HLT' if _any_road else 'CHECKBOX_DEHLT')
            if props.show_roads:
                col = sub.column(align=True)
                col.prop(props, "el_sBigActive", icon='CHECKBOX_HLT' if props.el_sBigActive else 'CHECKBOX_DEHLT')
                col.prop(props, "el_sMedActive", icon='CHECKBOX_HLT' if props.el_sMedActive else 'CHECKBOX_DEHLT')
                col.prop(props, "el_sSmallActive", icon='CHECKBOX_HLT' if props.el_sSmallActive else 'CHECKBOX_DEHLT')
                sub.prop(props, "el_sMultiplier")

        # --- PIN ---
        layout.prop(props, "show_pin", icon="TRIA_DOWN" if props.show_pin else "TRIA_RIGHT", emboss=False)
        if props.show_pin:
            box = layout.box()
            box.operator("tp3d.import_pin", text=_("Place Pin"), icon="PINNED")

            box.separator(factor=0.5)
            if temp.PREMIUMVERSION:
                box.prop(props, "cityname")
                box.operator("tp3d.city_coords", text=_("Pin on City"), icon="UNPINNED")
            else:
                box.prop(props, "cityname")
                box.operator("tp3d.terrain_dummy", text=_("Pin on City"), icon="LOCKED")

        # --- SPECIAL ---
        if temp.PREMIUMVERSION:
            layout.prop(props, "show_special", icon="TRIA_DOWN" if props.show_special else "TRIA_RIGHT", emboss=False)
            if props.show_special:
                box = layout.box()
                col = box.column(align=True)
                col.prop(props, "specialBlendFile")
                col.prop(props, "specialCollectionName", text="Collection")
                box.operator("tp3d.append_collection", text=_("Import + Generate"), icon="IMPORT")
                if props.specialBlendFile == "puzzles.blend":
                    box.operator("tp3d.append_collection_blank", text=_("Import Blank"), icon="IMPORT")
        else:
            layout.prop(props, "show_special", icon="LOCKED", emboss=False)
            if props.show_special:
                box = layout.box()
                col = box.column()
                col.label(text=_("Exclusive for Patreon Supporters"), icon='FUND')
                col.label(text=_("- Use Special Manual crafted Handtemplates"))
                col.label(text=_("- e.G Jigzaw Puzzle, Sliding Puzzle of your Map"))

        # --- POST PROCESS ---
        layout.prop(props, "show_postProcess", icon="TRIA_DOWN" if props.show_postProcess else "TRIA_RIGHT", emboss=False)
        if props.show_postProcess:
            box = layout.box()
            box.label(text=_("Manually export object after these actions"))

            sub = box.box()
            sub.label(text=_("Color Mountains"), icon='RNDCURVE')
            col = sub.column(align=True)
            col.prop(props, "mountain_treshold")
            col.operator("tp3d.color_mountain", text=_("Color Mountains"), icon="RNDCURVE")

            sub = box.box()
            sub.label(text=_("Contour Lines"), icon='ALIGN_JUSTIFY')
            col = sub.column(align=True)
            col.prop(props, "cl_thickness")
            col.prop(props, "cl_distance")
            col.prop(props, "cl_offset")
            col.operator("tp3d.contour_lines", icon="ALIGN_JUSTIFY")

            #sub = box.box()
            #sub.label(text=_("Rescale Elevation"), icon='DRIVER_DISTANCE')
            #row = sub.row(align=True)
            #row.prop(props, "rescaleMultiplier")
            #row.operator("wm.rescale", text=_("Rescale"))

            #sub = box.box()
            #sub.label(text=_("Extrude Terrain"), icon='EMPTY_SINGLE_ARROW')
            #col = sub.column(align=True)
            #col.prop(props, "thickenValue")
            #col.operator("wm.thicken", text=_("Extrude Terrain"), icon="EMPTY_SINGLE_ARROW")

            sub = box.box()
            sub.label(text=_("Magnet Holes"), icon='SNAP_OFF')
            row = sub.row(align=True)
            row.prop(props, "magnetHeight")
            row.prop(props, "magnetDiameter")
            sub.operator("tp3d.magnet_holes", text=_("Add Magnet Holes"), icon="SNAP_OFF")

            sub = box.box()
            sub.operator("tp3d.dovetail", text=_("Add Dovetail Cutouts"), icon="SHAPEKEY_DATA")

            sub = box.box()
            sub.label(text=_("Bottom Mark"), icon='SMALL_CAPS')
            col = sub.column(align=True)
            col.operator("tp3d.bottom_mark", text=_("Add Bottom Mark"), icon="SMALL_CAPS")
            col.prop(props, "bottomMarkCutout")

            sub = box.box()
            row = sub.row()
            row.label(text=_("SVG / Text Import"), icon='FILE_IMAGE')
            ln = row.operator("tp3d.info_video", text="", icon="QUESTION")
            ln.url = "https://www.youtube.com/@EmGi_"
            sub.prop(props, "svg_path")
            sub.operator("tp3d.import_svg", text=_("Import SVG"))
            sub.operator("tp3d.import_text", text=_("Place Text"), icon='FONT_DATA')

            sub = box.box()
            if temp.PREMIUMVERSION:
                sub.operator("tp3d.import_height_map", text=_("Import 2D Heightmap"), icon='IMAGE_DATA')
            else:
                sub.operator("tp3d.terrain_dummy", text=_("Create Heightmap"), icon="LOCKED")

        # --- PRESET ---
        layout.prop(props, "show_preset", icon="TRIA_DOWN" if props.show_preset else "TRIA_RIGHT", emboss=False)
        if props.show_preset:
            box = layout.box()
            box.prop(context.scene, "preset_list")
            box.operator("tp3d.load_preset", icon="PRESET")
            row = box.row(align=True)
            row.operator("tp3d.save_preset", icon="PRESET_NEW")
            row.operator("tp3d.delete_preset", icon="REMOVE")

        # --- API ---
        layout.prop(props, "show_api", icon="TRIA_DOWN" if props.show_api else "TRIA_RIGHT", emboss=False)
        if props.show_api:
            box = layout.box()
            box.prop(props, "api", icon="INTERNET")
            if props.api == "OPENTOPODATA":
                box2 = box.box()
                col = box2.column(align=True)
                col.prop(props, "dataset")
                col.separator(factor=0.5)
                col.label(text=_("If you hosted your own Version of Opentopodata:"))
                col.prop(props, "selfHosted")
            if props.api == "OPENTOPOGRAPHY":
                from .addon_preferences import get_prefs
                box2 = box.box()
                col = box2.column(align=True)
                col.prop(props, "openTopographyDataset")
                col.separator(factor=0.5)
                if not get_prefs().openTopographyApiKey:
                    col.label(text=_("API key required — set it in the addon preferences"), icon='ERROR')
                else:
                    col.label(text=_("API key set"), icon='CHECKMARK')
                col.operator("screen.userpref_show", text=_("Open Preferences"), icon='PREFERENCES')
            if props.api == "OPENTOPODATA" or props.api == "TERRAIN-TILES":
                col = box.column(align=True)
                col.prop(props, "disableCache")
                col.prop(props, "ccacheSize")
            box.separator(factor=0.5)
            box.label(text=_("Elements (Water,forest,...) runs on the Overpass API"))
            box.prop(props, "apiRetries")
            box.separator(factor=0.5)
            box.operator("tp3d.clear_cache", icon="BRUSH_DATA")

        # --- STATS ---
        layout.prop(props, "show_stats", icon="TRIA_DOWN" if props.show_stats else "TRIA_RIGHT", emboss=False)
        if props.show_stats:
            box = layout.box()
            box.label(text=_("Get Input Settings of Selected Generate Map"), icon='QUESTION')
            box.operator("tp3d.show_custom_props_popup", icon="QUESTION")
            box.separator(factor=0.5)
            box.label(text=_("Last Generation"), icon='TIME')
            col = box.column(align=True)
            col.label(text=props.o_verticesPath)
            col.label(text=props.o_verticesMap)
            col.label(text=props.o_mapScale)
            col.label(text=f"scaleHor: {props.sScaleHor}")
            col.label(text=f"Map Size: {props.sMapInKm}")
            col.label(text=props.o_time)
            box.separator(factor=0.5)
            col = box.column(align=True)
            col.label(text="Opentopodata:")
            col.label(text=props.o_apiCounter_OpenTopoData)
            col.label(text="OpenElevation:")
            col.label(text=props.o_apiCounter_OpenElevation)

        # --- ATTRIBUTION ---
        layout.prop(props, "show_attribution", icon="TRIA_DOWN" if props.show_attribution else "TRIA_RIGHT", emboss=False)
        if props.show_attribution:
            box = layout.box()
            col = box.column(align=True)
            col.label(text=_("Elevation data from OpenTopoData, using the SRTM and other datasets."))
            col.label(text=_("Elevation data from Open-Elevation, based on Shuttle Radar Topography Mission (SRTM) data © NASA."))
            col.label(text=_("Water, Forests, City data © OpenStreetMap contributors"))
            col.label(text=_("Terrain data from Mapzen, based on data © OpenStreetMap contributors, NASA SRTM, and USGS."))


class TP3D_PT_shapes(bpy.types.Panel):
    bl_label = "Additional Shape Settings"
    bl_idname = "TP3D_PT_shapes"
    bl_space_type = "VIEW_3D"
    bl_region_type = "UI"
    bl_category = "TrailPrint3D"
    
    def draw(self, context):
        layout = self.layout
        props = context.scene.tp3d  # Get properties

        
        #print(f"shape: {props.shape}")
        if props.shape in {"HEXAGON INNER TEXT", "HEXAGON OUTER TEXT", "OCTAGON OUTER TEXT", "HEXAGON FRONT TEXT", "MEDAL"}:

            #Add input fields
            layout.prop(props, "textFont")
            layout.prop(props, "textSizeTitle")
            layout.prop(props, "textSize")
            layout.separator()  # Adds a horizontal line
            layout.label(text = _("Plate text:"))

            if temp.PREMIUMVERSION:
                row = layout.row()
                split = row.split(factor=0.3)
                split.prop(props, "titleIcon", text = "")
                split.prop(props,"titlefield", text = "")
                row = layout.row()

                row = layout.row()
                split = row.split(factor=0.3)
                split.prop(props,"iconText1", text = "")
                split.prop(props, "textfield1", text = "")
                row = layout.row()
                split = row.split(factor=0.3)
                split.prop(props,"iconText2", text = "")
                split.prop(props, "textfield2", text = "")
                row = layout.row()
                split = row.split(factor=0.3)
                split.prop(props,"iconText3", text = "")
                split.prop(props, "textfield3", text = "")
            else:
                #row = layout.row()
                #row.enabled = False
                #row.label(text=_("Icons — Premium Feature"), icon='LOCKED')

                row = layout.row()
                split = row.split(factor=0.3)
                split.operator("tp3d.terrain_dummy", text=_('Icon'), icon='LOCKED')
                split.prop(props,"titlefield", text = "")
                row = layout.row()
                split = row.split(factor=0.3)
                split.operator("tp3d.terrain_dummy", text=_('Icon'), icon='LOCKED')
                split.prop(props, "textfield1", text = "")
                row = layout.row()
                split = row.split(factor=0.3)
                split.operator("tp3d.terrain_dummy", text=_('Icon'), icon='LOCKED')
                split.prop(props, "textfield2", text = "")
                row = layout.row()
                split = row.split(factor=0.3)
                split.operator("tp3d.terrain_dummy", text=_('Icon'), icon='LOCKED')
                split.prop(props, "textfield3", text = "")

            layout.prop(props, "plateThickness")
            layout.prop(props, "outerBorderSize")
            layout.prop(props, "plateInsertValue")
            layout.prop(props, "text_angle_preset")

            if props.shape in {"HEXAGON OUTER TEXT", "HEXAGON FRONT TEXT", "OCTAGON OUTER TEXT", "MEDAL"}:
                layout.prop(props, "plateBevel")


        else:
            layout.label(text = _("Only for Text based Shapes (like Hexagon Outer Text)"))



class TP3D_OT_show_custom_props_popup(bpy.types.Operator):
    bl_idname = "tp3d.show_custom_props_popup"
    bl_label = _("Generation Settings")
    bl_description = _("Show what Settings were used to Generate this Object (With Map object Selected)")
    bl_options = {'REGISTER'}

    MAX_PER_COLUMN = 25
    NORMAL_WIDTH = 400
    DOUBLE_WIDTH = 800

    def draw(self, context):
        layout = self.layout
        obj = context.active_object

        if not obj:
            layout.label(text= _("No active object."), icon="ERROR")
            return

        custom_props = [k for k in obj.keys() if not k.startswith("_")]

        if not custom_props:
            layout.label(text= _("No custom properties found. Please Select a Map"), icon="INFO")
            return

        total = len(custom_props)

        if total > self.MAX_PER_COLUMN:
            split = layout.split(factor=0.5)
            col1 = split.column(align=True)
            col2 = split.column(align=True)

            mid = (total + 1) // 2

            for col, chunk in zip((col1, col2), (custom_props[:mid], custom_props[mid:])):
                for key in chunk:
                    row = col.row()
                    row.label(text=key + ":", icon='DOT')
                    row.label(text=str(obj[key]))
        else:
            col = layout.column(align=True)
            for key in custom_props:
                row = col.row()
                row.label(text=key + ":", icon='DOT')
                row.label(text=str(obj[key]))

    def execute(self, context):
        return {'FINISHED'}

    def invoke(self, context, event):
        obj = context.active_object
        custom_props = [k for k in obj.keys() if not k.startswith("_")] if obj else []
        width = self.DOUBLE_WIDTH if len(custom_props) > self.MAX_PER_COLUMN else self.NORMAL_WIDTH
        return context.window_manager.invoke_props_dialog(self, width=width)








