#  Copyright (C) 2026  EmGi

# You are free to modify it under the terms of the GNU General Public License as published by the Free Software Foundation.
# You are free to use any models Generated by this Addon Commercially

import bpy
from bpy.app.translations import pgettext_iface as _  # For Translation of Text Required
from bpy.props import (
    BoolProperty,
    CollectionProperty,
    EnumProperty,
    FloatProperty,
    IntProperty,
    PointerProperty,
    StringProperty,
)

from . import constants as const
from . import temp, utils


def _slicer_profile_items(self, context) -> list[tuple[str, str, str]]:
    # Combine the description parts into one string
    desc = (
        "Use the built-in Bambu A1 template. "
        "Add your own profiles in Preferences → Add-ons → 3MF Format → Advanced"
    )
    items = [("NONE", "Built-in defaults", desc)]

    import importlib

    from .threemf_discovery import get_threemf_api

    _api = get_threemf_api()
    if _api is None:
        return items

    sp = importlib.import_module(".slicer_profiles", package=_api.__package__)
    for p in sp.list_profiles():
        detail = p.machine or p.vendor
        desc = (
            f"{detail} (from {p.source_file}). "
            "Add more profiles in Preferences → Add-ons → 3MF Format → Advanced"
        )
        items.append((p.name, p.name, desc))

    return items


def shape_callback(self, context):
    # print(f"Shape: {self.shape}")
    # if self.shape == "HEXAGON INNER TEXT" or self.shape == "HEXAGON OUTER TEXT" or self.shape =="OCTAGON OUTER TEXT" or self.shape == "HEXAGON FRONT TEXT":
    #    try:
    #        bpy.utils.register_class(panels.TP3D_P_Shapes)
    #    except:
    #        pass
    # else:
    #    try:
    #        bpy.utils.unregister_class(panels.TP3D_P_Shapes)
    #    except:
    #        pass
    pass


def get_special_blend_items(self, context):
    # puzzles.blend itself (the hand-crafted jigsaw/sliding-puzzle templates)
    # stays Premium-exclusive and is stripped from free builds by build.py --
    # unlike the interactive Jigsaw Puzzle Generator, which is free. Items must be a
    # callback (not a static default) so this list can change per-build.
    #
    # Dynamic-items EnumProperty can't take an explicit `default=` -- Blender
    # always initializes to whichever item comes first here. Putting
    # puzzles.blend first for Premium preserves the original default; free
    # builds fall back to holder.blend since puzzles.blend isn't an option.
    if temp.PREMIUMVERSION:
        return [
            ("puzzles.blend", "Jigzaw/Sliding Puzzles", "global"),
            ("holder.blend", "Map Holder", "Latitudes -60 to 60"),
            (
                "connectors.blend",
                "Map Connectors",
                "Continental USA, Hawaii, parts of Alaska",
            ),
        ]
    return [
        ("holder.blend", "Map Holder", "Latitudes -60 to 60"),
        (
            "connectors.blend",
            "Map Connectors",
            "Continental USA, Hawaii, parts of Alaska",
        ),
    ]


def generation_mode_update(self, context):
    self.use_multi_generation = self.generation_mode == "MULTI"


# Which text/plate/shell extras each base shape supports. "NONE" (plain shape,
# no overlay) must come first in every list -- see the shapeTextStyle
# comment for why. HEART has no entry here -- it has no extras to offer.
_SHELL_ITEM = (
    "SHELL",
    _("Shell"),
    _(
        "Snug protective shell around the map's sides and bottom, offset by the tolerance gap with a printable wall"
    ),
)

SHAPE_TEXT_STYLES = {
    "HEXAGON": [
        ("NONE", _("None"), _("Plain hexagonal map, no text overlay")),
        ("INNER TEXT", _("Inner text"), _("Hexagonal map with inserted text")),
        ("OUTER TEXT", _("Outer text"), _("Hexagonal map with backplate and text")),
        (
            "FRONT TEXT",
            _("Front text"),
            _("Hexagonal map with backplate and text on the front"),
        ),
        _SHELL_ITEM,
    ],
    "OCTAGON": [
        ("NONE", _("None"), _("Plain octagon map, no text overlay")),
        ("OUTER TEXT", _("Outer text"), _("Octagon map with backplate and text")),
        _SHELL_ITEM,
    ],
    "CIRCLE": [
        ("NONE", _("None"), _("Plain circular map, no text overlay")),
        (
            "OUTER TEXT",
            _("Outer text"),
            _("Circular map with backplate and curved text"),
        ),
        _SHELL_ITEM,
    ],
    "SQUARE": [
        ("NONE", _("None"), _("Plain rectangular map, no extras")),
        _SHELL_ITEM,
    ],
    "ELLIPSE": [
        ("NONE", _("None"), _("Plain ellipse map, no extras")),
        _SHELL_ITEM,
    ],
}


# Road type tiers shown in the Roads UIList. `road_id` is the stable lookup
# key (mirrors utils.osm.roads.TIER_TAGS) -- it is never translated and never
# shown, so lookups can't break if the display name changes with locale.
# Order here is the order rows are populated/displayed in.
ROAD_TYPE_DEFS = [
    (
        "highways",
        _("Highways"),
        "highway=motorway, motorway_link -- controlled-access highways",
    ),
    (
        "major",
        _("Major Roads"),
        "highway=trunk, primary, trunk_link, primary_link -- arterial roads just below highway grade",
    ),
    (
        "minor",
        _("Minor Roads"),
        "highway=secondary, tertiary, secondary_link, tertiary_link, unclassified",
    ),
    ("residential", _("Residential Roads"), "highway=residential, living_street"),
    (
        "service",
        _("Service Roads"),
        (
            "highway=service -- vehicle access roads to buildings, parking lots, business estates (see "
            "Key:service on the OSM wiki). Split out from Residential Roads since alley/driveway/"
            "parking_aisle ways are always filtered out of it (using OSM's own service=* sub-tag, not "
            "geometry) rather than being lumped in with named residential streets."
        ),
    ),
    (
        "footway",
        _("Footways/Sidewalks"),
        "highway=footway -- pedestrian sidewalks and paths, OSM's own separate non-vehicle category "
        "(see Key:highway on the OSM wiki). Kept separate by default since footways trace almost every "
        "street and are usually the biggest single source of visual clutter.",
    ),
    (
        "cycle_bridle",
        _("Cycle/Bridle Paths"),
        "highway=cycleway, bridleway -- dedicated bike and horse paths",
    ),
    (
        "track",
        _("Tracks"),
        "highway=track -- unpaved access tracks/fire roads. Often the one long rural trail a user "
        "actually wants, so this tier is exempt from the dense-road mapsize cutoff that drops "
        "Residential/Service/Footway/Cycle-Bridle roads on larger maps (see STREETS_PRIMARY_THRESHOLD).",
    ),
    (
        "path",
        _("Trails/Paths"),
        "highway=path -- generic multi-use/hiking trail, ambiguous length so kept in the normal "
        "dense-road mapsize cutoff rather than being exempted like Tracks.",
    ),
]

_ROAD_TYPE_IDS = {d[0] for d in ROAD_TYPE_DEFS}


class TP3D_RoadTypeItem(bpy.types.PropertyGroup):
    """One row of the Roads UIList. `name` (inherited) holds the translated
    display label; `road_id` is the stable, untranslated lookup key."""

    road_id: StringProperty()  # type: ignore
    active: BoolProperty(default=False)  # type: ignore
    description: StringProperty()  # type: ignore


def ensure_road_types(tp3d):
    """Populate/repair `tp3d.road_types` from ROAD_TYPE_DEFS.

    CollectionProperty starts empty on every new file/scene -- unlike an
    EnumProperty there's no static item list Blender can draw on its own, so
    this has to be called before the Roads UIList is drawn (and again after
    file load, in case an older file predates a tier being added/removed).
    Existing values are preserved by road_id; only missing ids are added and
    stale ids (from a future addon downgrade) are dropped.
    """
    existing = {item.road_id: item.active for item in tp3d.road_types}
    if existing.keys() == _ROAD_TYPE_IDS:
        return
    tp3d.road_types.clear()
    for road_id, label, desc in ROAD_TYPE_DEFS:
        item = tp3d.road_types.add()
        item.road_id = road_id
        item.name = label
        item.description = desc
        item.active = existing.get(road_id, False)


def get_road_active(tp3d, road_id: str) -> bool:
    """True if the given road tier (e.g. "highways", "track") is enabled.

    Deliberately NOT tp3d.road_types.get(road_id) -- bpy_prop_collection.get()
    matches by the item's `name` field (the translated display label, e.g.
    "Highways"), not by our separate `road_id` field ("highways"). That
    always misses, silently returning None -- which is why this used to
    return False unconditionally regardless of what was actually checked.
    """
    for item in tp3d.road_types:
        if item.road_id == road_id:
            return bool(item.active)
    return False


def set_road_active(tp3d, road_id: str, value: bool) -> None:
    for item in tp3d.road_types:
        if item.road_id == road_id:
            item.active = bool(value)
            return


def any_road_active(tp3d) -> bool:
    return any(item.active for item in tp3d.road_types)


def get_shape_text_style_items(self, context):
    # Items must be a callback (not a static list) since the available
    # styles depend on which base shape is currently selected.
    items = SHAPE_TEXT_STYLES.get(
        self.shape, [("NONE", _("None"), _("No text overlay available for this shape"))]
    )
    if not temp.PREMIUMVERSION:
        # Shell is Premium-exclusive -- stays visible in the dropdown (so free
        # users know it exists) but gets a lock icon and a "(Premium)" label.
        # Blender's Enum dropdown can't disable a single item outright, so
        # actually picking it is caught by shape_text_style_update below,
        # which snaps the selection back to NONE.
        items = [
            (ident, _("%s (Premium)") % label, desc, "LOCKED", i)
            if ident == "SHELL"
            else (ident, label, desc, "NONE", i)
            for i, (ident, label, desc) in enumerate(items)
        ]
    return items


def shape_text_style_update(self, context):
    if self.shapeTextStyle == "SHELL" and not temp.PREMIUMVERSION:
        self.shapeTextStyle = "NONE"
        utils.show_message_box(
            _("Shell is a Patreon-exclusive feature."), "INFO", _("Premium Feature")
        )
        return
    # shapeTextStyle is a dynamic-items EnumProperty (see get_shape_text_style_items),
    # so Blender stores it as a bare index -- the identifier it resolves to depends
    # on whichever items list is current when read. shape_update (below) needs the
    # identifier the user actually *picked*, independent of that reinterpretation,
    # so mirror it into a plain string every time it's set while self.shape hasn't
    # changed yet (i.e. here, where the items list still matches the selection).
    self.shapeTextStyleCache = self.shapeTextStyle


def shape_update(self, context):
    # Switching self.shape changes shapeTextStyle's item list. Because that
    # property is stored as an index, re-reading self.shapeTextStyle here would
    # silently reinterpret the old index against the new list (e.g. index 2 means
    # "Outer text" under Hexagon but "Shell" under Octagon) instead of reflecting
    # what the user actually had selected. Use the cached identifier string
    # instead: keep it if the new shape still offers that option, else fall back
    # to None.
    valid_styles = {
        ident for ident, _label, _desc in SHAPE_TEXT_STYLES.get(self.shape, [])
    }
    cached = self.shapeTextStyleCache
    if cached == "SHELL" and not temp.PREMIUMVERSION:
        self.shapeTextStyle = "NONE"
    elif cached in valid_styles:
        self.shapeTextStyle = cached
    else:
        self.shapeTextStyle = "NONE"


def element_source_update(self, context):
    # ESA WorldCover face-painting (paint_terrain_from_landcover) only runs
    # in PAINT elementMode -- the "Element handling" control is hidden
    # whenever WorldCover is selected (panels.py), so force the stored value
    # to match what that hidden state implies, rather than silently doing
    # nothing if elementMode was last left on SEPARATE/SINGLECOLORMODE_REMESH.
    if self.elementSource == "WORLDCOVER":
        self.elementMode = "PAINT"


def get_effective_shape(tp3d) -> str:
    """The full shape identifier generation.py/metadata.py operate on
    (e.g. "HEXAGON OUTER TEXT"), composed from the base shape dropdown and
    the text-style dropdown. Falls back to the bare base shape if no style
    is selected, or if the stored style isn't valid for the current base
    shape (e.g. left over from a different shape)."""
    base = "HEXAGON"
    if tp3d.shape != "":
        base = tp3d.shape
    style = tp3d.shapeTextStyle
    if style == "SHELL" and not temp.PREMIUMVERSION:
        # Guards against a SHELL value left over from a Premium session/preset
        # -- Shell is Premium-exclusive, so free builds always fall back to
        # the bare base shape instead of acting on a stale selection.
        return base
    valid_styles = {ident for ident, _label, _desc in SHAPE_TEXT_STYLES.get(base, [])}
    if style and style != "NONE" and style in valid_styles:
        return f"{base} {style}"
    return base


# Effective shapes that add a backplate with an outer border around the map
# (see the "outersize = size * (1 + outerBorderSize/100)" calc duplicated in
# HexagonOuterText/HexagonFrontText/OctagonOuterText/MedalText in
# text_objects.py, and the same set gating plateBevel/handleStyle in
# panels.py's TP3D_PT_shapes). "... INNER TEXT" has no border, so it's not here.
PLATE_SHAPES = {
    "HEXAGON OUTER TEXT",
    "HEXAGON FRONT TEXT",
    "OCTAGON OUTER TEXT",
    "CIRCLE OUTER TEXT",
}


def get_effective_footprint_size(tp3d):
    """The actual outer footprint size (mm) of the generated model. Shapes
    with a plate (see PLATE_SHAPES) are larger than objSize by the outer
    border, so anything scaled to fit the map (e.g. an imported holder) needs
    this instead of the bare objSize."""
    if get_effective_shape(tp3d) in PLATE_SHAPES:
        return tp3d.objSize * (1 + tp3d.outerBorderSize / 100)
    return tp3d.objSize


def estimate_map_km(tp3d):
    """Estimate the generated map's real-world km footprint from the cached
    GPX trail bounding box (set by TP3D_OT_pick_gpx_file at file-pick time --
    see utils.io_gpx.compute_gpx_bounds), for the live per-category size
    warnings in the Map Elements section. Returns None when no estimate is
    available (no GPX picked yet, or COORDINATES scale mode, which derives
    its bounds from the scaleLat/scaleLon fields directly rather than the
    trail's own extent).

    Reuses calculate_scale()'s own branch logic rather than re-deriving the
    FACTOR/SCALE formulas here -- see plan Finding 2d: one source of truth
    for "how big is the map", not a second copy that can drift from what
    generation actually computes."""
    if not tp3d.cachedTrailBoundsValid or tp3d.scalemode == "COORDINATES":
        return None
    coordinates = [
        (tp3d.cachedTrailMinLat, tp3d.cachedTrailMinLon),
        (tp3d.cachedTrailMaxLat, tp3d.cachedTrailMaxLon),
    ]
    scale = utils.calculate_scale(tp3d.objSize, coordinates, gen_type=0)
    if not scale:
        return None
    if bpy.app.debug:
        print(
            f"DEBUG: objSize={tp3d.objSize}, scale={scale}, raw_div={tp3d.objSize / scale}"
        )

    return tp3d.objSize / scale  # mm -> real-world km


def repair_invalid_shape(scene):
    """Files/sessions saved before the "... TEXT" shape variants were split
    out into shapeTextStyle may still have `shape` stored as one of those
    now-removed identifiers. Reading an EnumProperty whose stored index no
    longer exists in the (now trimmed, base-shapes-only) items list returns
    '' and logs a bpy.rna warning on every single access -- once per UI
    redraw, so it floods the console. Reset it once to a valid default so
    both the stored value and the warning spam go away."""
    tp3d = getattr(scene, "tp3d", None)
    if tp3d is not None and not tp3d.shape:
        tp3d.shape = "HEXAGON"


# Define a Property Group to store variables
class TP3D_PG_properties(bpy.types.PropertyGroup):
    file_path: StringProperty(
        name=_("File Path"),
        description=_("Select a GPX file"),
        default="",
        maxlen=1024,
    )  # type: ignore
    export_path: StringProperty(
        name=_("Export Path"),
        description=_("Where to save the STL file"),
        default="",
        maxlen=1024,
        subtype="DIR_PATH",  # Enables folder selection
    )  # type: ignore
    chain_path: StringProperty(
        name=_("Folder Path"),
        description=_("Select a folder that contains multiple GPX files"),
        default="",
        maxlen=1024,
        subtype="DIR_PATH",  # Enables folder selection
    )  # type: ignore
    trailName: StringProperty(
        name=_("Name"), default="", description=_("Leave empty to use the Filename")
    )  # type: ignore

    # Cached GPX trail bounding box, populated by TP3D_OT_pick_gpx_file at
    # file-pick time (cheap -- XML parse only, no network) and consumed by
    # estimate_map_km() for the live per-category size warnings in Map
    # Elements. SKIP_SAVE: this is derived/session data, not a real user
    # setting -- shouldn't be written into .blend files or presets.
    cachedTrailBoundsValid: BoolProperty(default=False, options={"SKIP_SAVE"})  # type: ignore
    cachedTrailMinLat: FloatProperty(default=0.0, options={"SKIP_SAVE"})  # type: ignore
    cachedTrailMaxLat: FloatProperty(default=0.0, options={"SKIP_SAVE"})  # type: ignore
    cachedTrailMinLon: FloatProperty(default=0.0, options={"SKIP_SAVE"})  # type: ignore
    cachedTrailMaxLon: FloatProperty(default=0.0, options={"SKIP_SAVE"})  # type: ignore

    shape: EnumProperty(
        name="",
        items=[
            ("HEXAGON", _("Hexagon"), _("Hexagonal map")),
            ("SQUARE", _("Rectangle"), _("Rectangular map")),
            ("CIRCLE", _("Circle"), _("Circular map")),
            ("OCTAGON", _("Octagon"), _("Octagon Map")),  # Premium
            ("ELLIPSE", _("Ellipse"), _("Ellipse Map")),  # Premium
            ("HEART", _("Heart"), _("Heart Map")),  # Premium
            ("GEOJSON", _("GeoJSON"), _("Import a custom GeoJSON shape")),
            ("SVG", _("SVG"), _("Import a custom SVG shape")),
        ],
        default="HEXAGON",
        update=shape_update,
    )  # type: ignore
    shapeTextStyle: EnumProperty(
        name="",
        description=_(
            "Add an extra (text/plate overlay or shell) to the selected shape"
        ),
        items=get_shape_text_style_items,
        update=shape_text_style_update,
        # Dynamic-items EnumProperty can't take an explicit `default=` -- see
        # get_special_blend_items above for why. "NONE" is first in every
        # per-shape list in SHAPE_TEXT_STYLES, so it's the default.
    )  # type: ignore
    shapeTextStyleCache: StringProperty(default="NONE", options={"HIDDEN"})  # type: ignore
    customFilePath: bpy.props.StringProperty(
        name="File Path",
        description="Path to the GeoJSON or SVG file",
        default="",
    )

    api: bpy.props.EnumProperty(
        name="api",
        items=[
            ("OPENTOPODATA", "Opentopodata", _("Slower but more accurate elevation")),
            (
                "OPEN-ELEVATION",
                "Open-Elevation",
                _("Faster but some regions are low quality"),
            ),
            ("TERRAIN-TILES", "Terrain-Tiles", _("Currently Fastest available set")),
            (
                "MAPTERHORN",
                "Mapterhorn",
                _(
                    "Mapterhorn terrain tiles — 512px WebP, Terrarium encoding, free & open-source"
                ),
            ),
            (
                "OPENTOPOGRAPHY",
                "OpenTopography",
                _("OpenTopography Global DEM API — requires API key for most datasets"),
            ),
        ],
        default="MAPTERHORN",
    )  # type: ignore

    openTopographyDataset: bpy.props.EnumProperty(
        name=_("Dataset"),
        items=[
            ("SRTMGL1", "SRTM GL1 (30m)", _("Global SRTM 30m resolution")),
            ("SRTMGL3", "SRTM GL3 (90m)", _("Global SRTM 90m resolution")),
            (
                "SRTM15Plus",
                "SRTM15+ (500m)",
                _("Global SRTM15+ 500m resolution — fastest download"),
            ),
            ("AW3D30", "ALOS AW3D30 (30m)", _("Global ALOS World 3D 30m")),
            ("NASADEM", "NASADEM (30m)", _("NASA Digital Elevation Model 30m")),
            ("COP30", "Copernicus 30m", _("Copernicus DEM 30m")),
            ("COP90", "Copernicus 90m", _("Copernicus DEM 90m")),
        ],
        default="SRTMGL1",
    )  # type: ignore

    apiRetries: IntProperty(
        name=_("Overpass API reuqest retries"),
        default=5,
        min=1,
        max=20,
        description=_("How many Retries per Request before canceling"),
    )  # type: ignore

    dataset: EnumProperty(
        name="Dataset",
        items=[
            ("srtm30m", "srtm30m", "Latitudes -60 to 60"),
            ("aster30m", "aster30m", "global"),
            ("ned10m", "ned10m", "Continental USA, Hawaii, parts of Alaska"),
            ("mapzen", "mapzen", "global"),
            ("nzdem8m", "nzdem8m", "New Zealand 8m"),
            ("eudem25m", "eudem25m", "Europe"),
        ],
        default="aster30m",
    )  # type: ignore

    scalemode: EnumProperty(
        name=_(""),
        items=[
            (
                "FACTOR", 
                _("Map Scale"), 
                _("Set a scale based on the Map size")
            ),
            (
                "COORDINATES",
                _("Coordinates"),
                _("Calculate the scale by using 2 Coordinates (Lat/lon)"),
            ),
        ],
        default="FACTOR",
    )  # type: ignore
    pathScale: FloatProperty(
        name=_("Path Scale"),
        default=0.8,
        min=0.01,
        description=_(
            "Scale of Path in Relation to the Mapsize/GlobalScale (depending on scalemode)"
        ),
    )  # type: ignore
    scaleLon1: FloatProperty(
        name="Lon1", default=0, description=_("The Longitude of the first coordinate")
    )  # type: ignore
    scaleLat1: FloatProperty(
        name="Lat1", default=0, description=_("The Latitude of the first coordinate")
    )  # type: ignore
    scaleLon2: FloatProperty(
        name="Lon2", default=0, description=_("The Longitude of the second coordinate")
    )  # type: ignore
    scaleLat2: FloatProperty(
        name="Lat2", default=0, description=_("The Latitude of the second coordinate")
    )  # type: ignore

    selfHosted: StringProperty(
        name=_("Self Hosted API"),
        default="",
        description=_(
            "Has to be same API format as Opentopodata.org (https://api.opentopodata.org/v1/)"
        ),
    )  # type: ignore

    objSize: IntProperty(
        name=_("Object Size in mm"),
        default=100,
        min=5,
        max=10000,
        description=_("Size of the map in mm"),
    )  # type: ignore
    num_subdivisions: IntProperty(
        name=_("Resolution"),
        default=8,
        min=1,
        soft_max=10,
        max=50,
        description=_(
            "(max recommended 8) Higher Number = more detailed terrain but slower generation. The slider caps at 10, but larger values can still be typed in directly."
        ),
    )  # type: ignore
    scaleElevation: FloatProperty(
        name=_("Elevation Scale"),
        default=1,
        min=0,
        max=10000,
        description=_(
            "Terrain height multiplier. 1.0 = true to scale, 2.0 = twice true height, 0.5 = half true height"
        ),
    )  # type: ignore
    pathThickness: FloatProperty(
        name=_("Trail Width"),
        default=1.2,
        min=0.1,
        max=5,
        description=_("Thickness of the path in mm"),
    )  # type: ignore
    shapeRotation: IntProperty(
        name=_("ShapeRotation"),
        default=0,
        min=-360,
        max=360,
        description=_("Rotation of the shape"),
    )  # type: ignore
    overwritePathElevation: BoolProperty(
        name=_("Overwrite Path Elevation"),
        default=True,
        description=_("Cast each point of the trail onto the Terrain Mesh"),
    )  # type: ignore
    o_verticesPath: StringProperty(name="Path vertices ", default="")  # type: ignore
    o_verticesMap: StringProperty(name="Path Map ", default="")  # type: ignore
    o_mapScale: StringProperty(name="Map Scale", default="")  # type: ignore
    o_time: StringProperty(name="TimeTook", default="")  # type: ignore
    o_apiCounter_OpenTopoData: StringProperty(
        name="apiCounter_OpenTopodata", default="API Limit: ---/1000 daily"
    )  # type: ignore
    o_apiCounter_OpenElevation: StringProperty(
        name="apiCounter_OpenElevation", default="API Limit: ---/1000 monthly"
    )  # type: ignore
    o_mapsGenerated: StringProperty(name="MapsGenerated", default="")  # type: ignore
    o_centerx: FloatProperty(
        name=_("Center X"), default=0, description=_("X Center of the Path")
    )  # type: ignore
    o_centery: FloatProperty(
        name=_("Center Y"), default=0, description=_("Y Center of the Path")
    )  # type: ignore

    magnetHeight: FloatProperty(
        name=_("Magnet Height"),
        default=2.5,
        description=_("Height of the Holes for Magnets"),
    )  # type: ignore
    magnetDiameter: FloatProperty(
        name=_("Magnet Diameter"),
        default=6.3,
        description=_("Diameter of the Holes for Magnets"),
    )  # type: ignore

    bottomMarkCutout: BoolProperty(
        name=_("Bottom Mark Cutout"),
        default=False,
        description=_("Creates Bottom mark as a Cutout"),
    )  # type: ignore

    ellipseRatio: FloatProperty(
        name=_("Ellipse Aspect Ratio"),
        default=0.75,
        description=_("0.75 means the ellipse height is 0.75 x objSize"),
    )  # type: ignore
    rectangleHeight: IntProperty(
        name=_("Rectangle Height"),
        default=100,
        description=_("Height of the Rectangle"),
    )  # type: ignore

    textFont: StringProperty(
        name=_("Font"),
        description=_("Select a file"),
        default="",
        maxlen=1024,
        subtype="FILE_PATH",  # Enables file selection
    )  # type: ignore
    textSize: IntProperty(name=_("Text Size"), default=5, min=0, max=1000)  # type: ignore
    textSizeTitle: IntProperty(
        name=_("Title Text Size"),
        default=0,
        min=0,
        max=1000,
        description=_("Keep 0 to use value from 'Text Size'"),
    )  # type: ignore
    titlefield: StringProperty(
        name=_("title"),
        default="{name}",
        description=_(
            "Codes = | {name} | {length} | {elevation} |{date} | {speed} | {scale}"
        ),
    )  # type: ignore
    textfield1: StringProperty(
        name=_("text1"),
        default="{length}",
        description=_(
            "Codes = | {name} | {length} | {elevation} |{date} | {speed} | {scale}"
        ),
    )  # type: ignore
    textfield2: StringProperty(
        name=_("text2"),
        default="{elevation}",
        description=_(
            "Codes = | {name} | {length} | {elevation} |{date} | {speed} | {scale}"
        ),
    )  # type: ignore
    textfield3: StringProperty(
        name=_("text3"),
        default="{duration}",
        description=_(
            "Codes = | {name} | {length} | {elevation} |{date} | {speed} | {scale}"
        ),
    )  # type: ignore
    textfield4: StringProperty(
        name=_("text4"),
        default="",
        description=_(
            "Codes = | {name} | {length} | {elevation} |{date} | {speed} | {scale}"
        ),
    )  # type: ignore
    textfield5: StringProperty(
        name=_("text5"),
        default="",
        description=_(
            "Codes = | {name} | {length} | {elevation} |{date} | {speed} | {scale}"
        ),
    )  # type: ignore
    titleIcon: EnumProperty(
        name="Title Icon",
        items=[
            ("cycling", _("Cycling Icon"), _("Cycling Icon before the Title")),
            ("hiking", _("Hiking Icon"), _("Hiking Icon before the Title")),
            ("running", _("Running Icon"), _("Running Icon before the Title")),
            ("swimming", _("Swimming Icon"), _("Swimming Icon before the Title")),
            ("skiing", _("Skiing Icon"), _("Skiing Icon before the Title")),
            (
                "snowboarding",
                _("Snowboarding Icon"),
                _("Snowboarding Icon before the Title"),
            ),
            ("kajak", _("Kayak Icon"), _("Kayak Icon before the Title")),
            ("no", _("No Icon"), _("No icon before the Title")),
        ],
        default="no",
    )  # type: ignore
    iconText1: EnumProperty(
        name="Text 1Icon",
        items=[
            ("distance", _("Distance Icon"), _("Distance Icon before the Text")),
            ("elevation", _("Elevation Icon"), _("Elevation Icon before the Text")),
            ("time", _("Time Icon"), _("Time icon before the Text")),
            ("speed", _("Speed Icon"), _("Speed icon before the Text")),
            ("date", _("Date Icon"), _("Date icon before the Text")),
            ("no", _("No Icon"), _("No icon before the Text")),
        ],
        default="distance",
    )  # type: ignore
    iconText2: EnumProperty(
        name=_("Text 2 Icon"),
        items=[
            ("distance", _("Distance Icon"), _("Distance Icon before the Text")),
            ("elevation", _("Elevation Icon"), _("Elevation Icon before the Text")),
            ("time", _("Time Icon"), _("Time icon before the Text")),
            ("speed", _("Speed Icon"), _("Speed icon before the Text")),
            ("date", _("Date Icon"), _("Date icon before the Text")),
            ("no", _("No Icon"), _("No icon before the Text")),
        ],
        default="elevation",
    )  # type: ignore
    iconText3: EnumProperty(
        name=_("Text 3 Icon"),
        items=[
            ("distance", _("Distance Icon"), _("Distance Icon before the Text")),
            ("elevation", _("Elevation Icon"), _("Elevation Icon before the Text")),
            ("time", _("Time Icon"), _("Time icon before the Text")),
            ("speed", _("Speed Icon"), _("Speed icon before the Text")),
            ("date", _("Date Icon"), _("Date icon before the Text")),
            ("no", _("No Icon"), _("No icon before the Text")),
        ],
        default="time",
    )  # type: ignore
    iconText4: EnumProperty(
        name="Text 4 Icon",
        items=[
            ("distance", _("Distance Icon"), _("Distance Icon before the Text")),
            ("elevation", _("Elevation Icon"), _("Elevation Icon before the Text")),
            ("time", _("Time Icon"), _("Time icon before the Text")),
            ("speed", _("Speed Icon"), _("Speed icon before the Text")),
            ("date", _("Date Icon"), _("Date icon before the Text")),
            ("no", _("No Icon"), _("No icon before the Text")),
        ],
        default="no",
    )  # type: ignore
    iconText5: EnumProperty(
        name="Text 5 Icon",
        items=[
            ("distance", _("Distance Icon"), _("Distance Icon before the Text")),
            ("elevation", _("Elevation Icon"), _("Elevation Icon before the Text")),
            ("time", _("Time Icon"), _("Time icon before the Text")),
            ("speed", _("Speed Icon"), _("Speed icon before the Text")),
            ("date", _("Date Icon"), _("Date icon before the Text")),
            ("no", _("No Icon"), _("No icon before the Text")),
        ],
        default="no",
    )  # type: ignore

    svg_path: StringProperty(
        name=_("SVG Path"),
        description=_("Select a .SVG file"),
        default="",
        maxlen=1024,
    )  # type: ignore

    # overwriteLength: StringProperty(name= _("text1"), default = "")
    # overwriteHeight: StringProperty(name= _("text2"), default = "")
    # overwriteTime: StringProperty(name= _("text3"), default = "")

    outerBorderSize: IntProperty(
        name=_("BorderSize in %"),
        default=20,
        min=0,
        max=1000,
        description=_("Only for Shapes with Plate"),
    )  # type: ignore
    text_angle_preset: IntProperty(
        name=_("Text Angle"),
        description=_("Rotate Text on Shape"),
        default=0,
        min=0,
        max=260,
    )  # type: ignore
    plateThickness: FloatProperty(
        name=_("plateThickness"),
        default=5,
        description=_("Thickness of the Additional Plate"),
    )  # type: ignore
    plateInsertValue: FloatProperty(
        name=_("plateInsertValue"),
        default=0,
        description=_("Depth of Cutout for the Map in the Plate, 0  to ignore"),
    )  # type: ignore
    plateBevel: FloatProperty(
        name=_("Plate Bevel"),
        default=0.0,
        min=0.0,
        max=50.0,
        description=_("Bevel the top and bottom edges of the plate (0 to disable)"),
    )  # type: ignore
    handleStyle: EnumProperty(
        name=_("Handle"),
        items=[
            ("NONE", _("None"), _("No handle")),
            (
                "ROUND",
                _("Round"),
                _("A round cylinder handle on top of the plate, like a medal"),
            ),
            (
                "FLAT",
                _("Flat"),
                _("A flat bar handle on top of the plate, like a medal"),
            ),
        ],
        default="NONE",
    )  # type: ignore
    shellWallThickness: FloatProperty(
        name=_("Shell Wall Thickness"),
        default=2.0,
        min=0.1,
        description=_("Thickness of the Shell extra's side walls"),
    )  # type: ignore

    tileSpacing: FloatProperty(
        name=_("tileSpacing"),
        default=0,
        description=_("Distance between Tiles when Extending"),
    )  # type: ignore

    minThickness: FloatProperty(
        name=_("minThickness"),
        default=2,
        min=0.5,
        max=1000,
        description=_("Additional Thickness on lowest point"),
    )  # type: ignore
    xTerrainOffset: FloatProperty(
        name=_("xTerrainOffset"),
        default=0,
        description=_("Gives the map an Offset in X-Direction from the path"),
    )  # type: ignore
    yTerrainOffset: FloatProperty(
        name=_("yTerrainOffset"),
        default=0,
        description=_("Gives the map an Offset in Y-Direction from the path"),
    )  # type: ignore

    rescaleMultiplier: FloatProperty(name=_("scale"), default=1, min=0, max=10000)  # type: ignore
    thickenValue: FloatProperty(
        name=_("thickenValue"), default=1, description=_("Makes your Map 1mm thicker")
    )  # type: ignore
    elevationMode: EnumProperty(
        name=_("Elevation Mode"),
        items=[
            (
                "PROPORTIONAL",
                _("Proportional"),
                _(
                    "Terrain height stays true to the model's horizontal scale, exaggerated by Elevation Exaggeration"
                ),
            ),
            (
                "FIXED",
                _("Fixed Height"),
                _(
                    "Terrain height is normalized so the highest and lowest points span a fixed target height, independent of horizontal scale"
                ),
            ),
        ],
        default="PROPORTIONAL",
        description=_(
            "How the real-world elevation data is converted into terrain height on the model"
        ),
    )  # type: ignore
    fixedHeightMM: FloatProperty(
        name=_("Target Peak-to-Valley Height"),
        default=10,
        min=0.1,
        max=1000,
        description=_(
            "Peak-to-valley terrain height in mm when Elevation Mode is Fixed Height. Elevation Exaggeration still multiplies on top of this"
        ),
    )  # type: ignore
    smoothTerrainTop: BoolProperty(
        name=_("Smooth Terrain"),
        default=False,
        description=_(
            "Smooth the Terrain. Useful if your Terrain looks blocky or has weird Grid lines"
        ),
    )  # type: ignore
    smoothTerrainStrength: IntProperty(
        name=_("Strength"),
        default=2,
        min=1,
        max=10,
        description=_(
            "Number of smoothing passes applied to the terrain top surface. Higher = smoother but less detailed"
        ),
    )  # type: ignore
    # Sept. 11, 2026: Officially renaming "SingleColorMode" to "Single Extruder Mode"
    singleColorMode: BoolProperty(
        name=_("Single Extruder Mode Trail"),
        default=False,
        description=_("Enable this if you don't have a Multicolor printer"),
    )  # type: ignore
    singleColorModeHeight: FloatProperty(
        name=_("Trail Height"),
        default=0.4,
        min=0.0,
        max=10.0,
        description=_(
            "How far the SCM trail strip rises above the terrain surface (mm). 0 = flush with terrain. Works the same as Road Height."
        ),
    )  # type: ignore
    tolerance: FloatProperty(
        name=_("Trail Tolerance"),
        default=0.2,
        description=_(
            "Controls the clearance around the Trail for the Single Extruder Mode"
        ),
        min=0,
    )  # type: ignore
    toleranceElements: FloatProperty(
        name=_("Element Tolerance"),
        default=0.12,
        description=_(
            "Controls the clearance around the Elements (Water, Forest) for the Single Extruder Mode"
        ),
        min=0,
    )  # type: ignore
    disableCache: BoolProperty(
        name=_("disableCache"),
        default=False,
        description=_("Disable cache if you encounter random holes in your mesh"),
    )  # type: ignore
    disableElevationOutlierFix: BoolProperty(
        name=_("Disable Buggy Elevation Fixes"),
        default=False,
        description=_(
            "Disable automatic correction of statistically outlying elevation values. Enable this if a real peak/valley is being incorrectly flattened"
        ),
    )  # type: ignore
    ccacheSize: IntProperty(name=_("Cache Size"), default=50000, min=0)  # type: ignore
    indipendendTiles: BoolProperty(
        name=_("IndipendendTiles"),
        default=False,
        description=_("Tile minThickness is independent from other tiles"),
    )  # type: ignore

    elementMode: EnumProperty(
        name="",
        items=[
            ("PAINT", _("Paint on Map"), _("Paint the Elements onto the map")),
            (
                "SINGLECOLORMODE_REMESH",
                _("Single Extruder Mode"),
                _("Use this if you are using a single extruder printer for printing"),
            ),
        ],
        default="PAINT",
    )
    tex_use_texture: BoolProperty(
        name=_("Create a texture"),
        default=bool(temp.has3mf),
        description="Create a texture instead of painting individual faces.",
    )
    tex_include_roads: BoolProperty(  # type: ignore
        name=_("Roads in texture"),
        default=False,
        description=_(
            "Rasterize the road footprint into the paint texture (terrain under roads coloured black)"
        ),
    )
    tex_include_trail: BoolProperty(  # type: ignore
        name=_("Trail in texture"),
        default=False,
        description=_(
            "Rasterize the trail footprint into the paint texture (terrain under trail coloured red)"
        ),
    )
    tex_resolution: IntProperty(
        name=_("Resolution"),
        description="Customize the image resolution used when creating the texture.",
        step=1024,
        min=1024,
        default=2048,
        max=8192,
    )
    elementModeInset: FloatProperty(
        name=_("Clip Inset"),
        default=2.0,
        min=0.0,
        description=_("Thickness of solid frame for SCM-elements"),
    )  # type: ignore
    col_osmSmoothing: FloatProperty(
        name=_("Element Smoothing"),
        default=0.0,
        min=0.0,
        max=1.0,
        subtype="FACTOR",
        description=_(
            "Rounds element polygons, smoothing their edges and making them easier to print.",
        ),
    )  # type: ignore
    elementChoice: BoolProperty(
        name=_("Use Elements"),
        default=False,
        description=_("Enable this if you want to generate a map with elements."),
    )  # type: ignore
    elementSource: EnumProperty(
        name=_(""),
        items=[
            (
                "OSM",
                _("OSM"),
                _(
                    "Fetch water, forests, farmland, and other elements from OpenStreetMap/Overpass"
                ),
            ),
            (
                "WORLDCOVER",
                _("ESA WorldCover"),
                _(
                    "Color the terrain from ESA WorldCover's land-cover classification instead of individual OSM element toggles. Roads and Buildings still come from OSM."
                ),
            ),
        ],
        default="OSM",
        update=element_source_update,
    )  # type: ignore

    col_wArea: FloatProperty(
        name=_("Threshold"),
        default=1,
        description=_("Water bodies smaller than the threshold won't be included"),
    )  # type: ignore
    col_wStreamWidth: FloatProperty(
        name=_("Waterway Width Multiplier"),
        default=1.0,
        min=0.1,
        max=100.0,
        description=_("Adjusts the thickness of all waterways, including Major Rivers."),
    )  # type: ignore
    col_wFlattenTop: BoolProperty(
        name=_("Flatten Water Surface"),
        default=True,
        description=_(
            "Flatten each water body's top surface to its own median height, giving it a flat bottom instead of following every terrain bump. Only applies in Separate Objects and Single-Color mode -- has no effect in Paint on Map mode"
        ),
    )  # type: ignore
    col_wInsert: FloatProperty(
        name=_("Insert"),
        default=0,
        min=0.0,
        description=_(
            "Sink the water piece this many mm lower in Z (its cutout in the terrain goes the same amount deeper, thickness unchanged). Only applies in Separate Objects and Single-Color mode"
        ),
    )  # type: ignore
    col_wBodiesActive: BoolProperty(
        name=_("Water Bodies"),
        default=False,
        description=_("Lakes, ponds, reservoirs, and wide river areas"),
    )  # type: ignore
    col_wMinorActive: BoolProperty(
        name=_("Minor Waterways"),
        default=False,
        description=_(
            "All linear paths including streams, canals, and ditches. Does not include Major Rivers.",
        ),
    )  # type: ignore
    col_wMajorActive: BoolProperty(
        name=_("Major Rivers"),
        default=False,
        description=_(
            "Major named rivers, rivers with significant waterway tags"
        ),
    )  # type: ignore
    col_fActive: BoolProperty(
        name=_("Include Forests"),
        default=False,
        description=_("Skipped automatically above %skm map size")
        % const.FOREST_MAXSIZE,
    )  # type: ignore
    col_fArea: FloatProperty(
        name=_("Threshold"),
        default=10,
        description=_("Forests smaller than the threshold won't be included"),
        min=0,
    )  # type: ignore
    col_scrActive: BoolProperty(
        name=_("Include Scree"),
        default=False,
        description=_(
            _("Rocky/stony terrain. Skipped automatically above %skm map size")
            % const.SCREE_MAXSIZE
        ),
    )  # type: ignore
    col_scrArea: FloatProperty(
        name=_("Threshold"),
        default=1,
        description=_("Scree patches smaller than the threshold won't be included"),
        min=0,
    )  # type: ignore
    col_cActive: BoolProperty(
        name=_("Include City Boundaries"),
        default=False,
        description=_("Skipped automatically above %skm map size") % const.CITY_MAXSIZE,
    )  # type: ignore
    col_cArea: FloatProperty(
        name=_("Threshold"),
        default=1,
        description=_("Cities smaller than the threshold won't be included"),
        min=0,
    )  # type: ignore
    col_grActive: BoolProperty(
        name=_("Include Greenspaces"),
        default=False,
        description=_(
            _(
                "Parks, gardens, grass and other urban green areas. Skipped automatically above %skm map size"
            )
            % const.GREENSPACE_MAXSIZE
        ),
    )  # type: ignore
    col_grArea: FloatProperty(
        name=_("Threshold"),
        default=1,
        description=_("Greenspaces smaller than the threshold won't be included"),
        min=0,
    )  # type: ignore
    col_faActive: BoolProperty(
        name=_("Include Farmland"),
        default=False,
        description=_(
            _(
                "Fetches landuse=farmland and landuse=farmyard. Skipped automatically above %skm map size"
            )
            % const.FARMLAND_MAXSIZE
        ),
    )  # type: ignore
    col_faArea: FloatProperty(
        name=_("Threshold"),
        default=1,
        description=_("Farmland patches smaller than the threshold won't be included"),
        min=0,
    )  # type: ignore
    col_glActive: BoolProperty(
        name=_("Include Glaciers"),
        default=False,
        description=_(
            _("Skipped automatically above %skm map size") % const.GLACIER_MAXSIZE
        ),
    )  # type: ignore
    col_glArea: FloatProperty(
        name=_("Threshold"),
        default=1,
        description=_("Glaciers smaller than the threshold won't be included"),
        min=0,
    )  # type: ignore
    col_KeepManifold: BoolProperty(
        name=_("Keep Non-Manifold Objects"),
        default=False,
        description=_("Keep Broken/Non-Manifold objects"),
    )  # type: ignore
    # ESA WorldCover per-category color toggles -- unlike col_fActive/col_wBodiesActive/
    # etc. above (which gate whether OSM fetches a category's polygons at all, and are
    # only consulted when elementSource == "OSM"), these gate whether an already-
    # classified WorldCover category keeps its real color or falls back to the base
    # color (see satellite.py's landcover_effective_material(), used by both
    # paint_terrain_from_landcover() and texture.py's setup_paint_texture()). Water/
    # Forest/Mountain default on (the categories that read clearly against the base
    # terrain color); City/Greenspace/Farmland/Glacier default off since WorldCover's
    # own classification is coarse enough there to look noisy/inaccurate out of the box.
    col_lcForestActive: BoolProperty(
        name=_("Forest"),
        default=True,
        description=_(
            "Tree cover and mangroves keep their forest color; disable to fall back to the base color"
        ),
    )  # type: ignore
    col_lcGreenspaceActive: BoolProperty(
        name=_("Greenspace"),
        default=False,
        description=_(
            "Shrubland and grassland keep their greenspace color; disable to fall back to the base color"
        ),
    )  # type: ignore
    col_lcFarmlandActive: BoolProperty(
        name=_("Farmland"),
        default=False,
        description=_(
            "Cropland keeps its farmland color; disable to fall back to the base color"
        ),
    )  # type: ignore
    col_lcCityActive: BoolProperty(
        name=_("City"),
        default=False,
        description=_(
            "Built-up areas keep their city color; disable to fall back to the base color"
        ),
    )  # type: ignore
    col_lcMountainActive: BoolProperty(
        name=_("Mountain"),
        default=True,
        description=_(
            "Bare/sparse vegetation and moss/lichen keep their mountain color; disable to fall back to the base color"
        ),
    )  # type: ignore
    col_lcGlacierActive: BoolProperty(
        name=_("Glacier"),
        default=False,
        description=_(
            "Snow and ice keep their glacier color; disable to fall back to the base color"
        ),
    )  # type: ignore
    col_lcWaterActive: BoolProperty(
        name=_("Water"),
        default=True,
        description=_(
            "Permanent water bodies and herbaceous wetland keep their water color; disable to fall back to the base color"
        ),
    )  # type: ignore
    el_bActive: BoolProperty(
        name=_("Include Buildings"),
        default=False,
        description=_(
            f"Skipped automatically above {const.BUILDINGS_MAXSIZE}km map size"
        ),
    )  # type: ignore
    el_bHeightMultiplier: FloatProperty(
        name=_("Height Multiplier"),
        default=1.0,
        min=0.01,
        soft_max=10.0,
        description=_("Multiplies building height"),
    )  # type: ignore
    el_bMinPrintMM: FloatProperty(
        name=_("Min Footprint (mm)"),
        default=0.15,
        min=0.0,
        soft_max=5.0,
        precision=2,
        description=_(
            "Buildings whose printed footprint side is smaller than this (in model mm) are skipped. Scale-aware: a larger real-world building on a bigger-km map prints smaller, so this threshold naturally culls more on larger maps."
        ),
    )  # type: ignore

    el_sMultiplier: FloatProperty(
        name=_("Width Multiplier"),
        default=1,
        min=0.01,
        soft_max=100.0,
        description=_("To make Roads thicker or thinner"),
    )  # type: ignore
    el_sHeight: FloatProperty(
        name=_("Height"),
        default=0.4,
        min=0.0,
        description=_("Height of road geometry above terrain"),
    )  # type: ignore
    el_sCutTolerance: FloatProperty(
        name=_("Tolerance"),
        default=0.2,
        min=0.0,
        description=_(
            "Extra clearance added around roads when cutting their footprint out of terrain/elements in Single Extruder Mode, so the printed road piece seats without an overly tight or impossible fit."
        ),
    )  # type: ignore
    el_sCutDepth: FloatProperty(
        name=_("Depth"),
        default=0.05,
        min=0.0,
        description=_(
            "Extra depth added below the road's bottom face when cutting its slot in Single Extruder Mode. By default this value attempts to not cut all the way through any one element."
        ),
    )  # type: ignore

    show_water: BoolProperty(name=_("Water & Ocean"), default=False)  # type: ignore
    show_roads: BoolProperty(name=_("Roads"), default=False)  # type: ignore
    road_types: CollectionProperty(type=TP3D_RoadTypeItem)  # type: ignore
    road_types_index: IntProperty(default=0)  # type: ignore
    el_oActive: BoolProperty(
        name=_("Include Ocean"),
        default=False,
        description=_("Generate ocean surface cut along the coastline. Experimental"),
    )  # type: ignore
    el_oMinIslandArea: FloatProperty(
        name=_("Min Island Area"),
        default=2.0,
        min=0.0,
        soft_max=100.0,
        description=_(
            "Islands smaller than this area (in map units²) are not punched out of the ocean. At a 100mm map size, 1 map unit ≈ 1mm on the print, so the default 2.0 ≈ a ~1.4×1.4mm patch. Set to 0 to punch all islands."
        ),
    )  # type: ignore
    el_oRdpEpsilon: FloatProperty(
        name=_("Coastline Simplify"),
        default=0.1,
        min=0.0,
        soft_max=2.0,
        precision=3,
        description=_(
            "Douglas-Peucker simplification tolerance (map units) applied to the coastline before building the ocean. Higher = fewer points but can introduce self-intersections on convoluted coasts. Set to 0 to disable simplification. Testing aid."
        ),
    )  # type: ignore
    el_wcMinFeatureArea: FloatProperty(
        name=_("Min Feature Area"),
        default=2.0,
        min=0.0,
        soft_max=100.0,
        description=_(
            "Land-cover regions smaller than this area (map units²) are merged into whichever neighboring class actually surrounds them, instead of showing up as an isolated fleck. At a 100mm map size, 1 map unit ≈ 1mm on the print, so the default 2.0 ≈ a ~1.4×1.4mm patch — the same convention as Min Island Area above. Set to 0 to disable and use WorldCover's raw per-pixel classification."
        ),
    )  # type: ignore
    mountain_treshold: IntProperty(
        name=_("Mountain Threshold"),
        default=60,
        min=0,
        max=100,
        subtype="PERCENTAGE",
        description=_("Height Threshold to Color Mountains"),
    )  # type: ignore
    cl_thickness: FloatProperty(
        name=_("Contour Line Thickness (mm)"),
        default=0.2,
        description=_("Thickness of the Contour Line"),
    )  # type: ignore
    cl_distance: FloatProperty(
        name=_("Contour Line distance"),
        default=2,
        description=_("Distance between Contour lines"),
    )  # type: ignore
    cl_offset: FloatProperty(
        name=_("Contour Line offset"),
        default=0.0,
        description=_("Offset of the Contour lines"),
    )  # type: ignore
    cl_useRealMeters: BoolProperty(
        name=_("Use Real-World Meters"),
        default=True,
        description=_(
            "Interpret the Contour Line distance/offset as real-world elevation meters instead of mm on the printed model"
        ),
    )  # type: ignore

    generation_mode: EnumProperty(
        name="Generation Mode",
        items=[
            ("GENERATION", _("Trail"), _("Single GPX file generation")),
            ("MULTI", _("Multi Trail"), _("Chain multiple GPX files")),
            ("TERRAIN", _("Terrain"), _("Generate terrain without GPX")),
        ],
        default="GENERATION",
        update=generation_mode_update,
    )  # type: ignore

    show_create_settings: BoolProperty(name=_("General Settings"), default=True)  # type: ignore
    show_terrain_files: BoolProperty(name=_("Files"), default=True)  # type: ignore
    show_export: BoolProperty(name=_("Export"), default=True)  # type: ignore
    disable_auto_export: BoolProperty(
        name=_("Disable Auto Export"),
        default=False,
        description=_("Don't automatically export files after generation"),
    )  # type: ignore
    disable_3mf_export: BoolProperty(
        name=_("Disable 3MF Export"),
        default=False,
        description=_("Don't use 3MF format even if the addon is installed"),
    )  # type: ignore
    keep_positions: BoolProperty(
        name=_("Keep positions during export"),
        default=False,
        description=_(
            "Enable this if you want the every item to keep it's position, instead of letting each piece remain separate in the slicer."
        ),
    )
    slicer_profile_name: EnumProperty(  # type: ignore
        name=_("Slicer Profile"),
        items=_slicer_profile_items,
        description=_(
            "Printer/filament profile embedded in the 3MF export. Add profiles in Preferences \u2192 Add-ons \u2192 3MF Format \u2192 Advanced"
        ),
    )

    show_stats: BoolProperty(name=_("Additional Info"), default=False)  # type: ignore
    show_coloring: BoolProperty(name=_("Elements"), default=False)  # type: ignore
    show_chain: BoolProperty(name=_("Multi Generation"), default=False)  # type: ignore
    use_multi_generation: BoolProperty(name=_("Multi Generation"), default=False)  # type: ignore
    show_map: BoolProperty(name=_("Map"), default=False)  # type: ignore
    show_ags: BoolProperty(name=_("Advanced Generation Settings"), default=False)  # type: ignore
    show_pin: BoolProperty(name=_("Pin"), default=False)  # type: ignore
    show_special: BoolProperty(name=_("Special"), default=False)  # type: ignore
    show_postProcess: BoolProperty(name=_("Post Process"), default=False)  # type: ignore
    show_api: BoolProperty(name=_("API"), default=False)  # type: ignore
    show_attribution: BoolProperty(name=_("Attribution"), default=False)  # type: ignore
    show_preset: BoolProperty(name=_("Preset"), default=False)  # type: ignore

    cityname: StringProperty(
        name=_("Cityname"), default="Berlin", description=_("Get coordinates of a City")
    )  # type: ignore
    pinLat: FloatProperty(name=_("Latitude"), default=48.00)  # type: ignore
    pinLon: FloatProperty(name=_("Longitude"), default=8.00)  # type: ignore

    pinCutout: BoolProperty(
        name=_("Pin Cutout"),
        default=False,
        description=_(
            "When placing a pin, also cut a matching socket into the map and elements at the pin's position, so the printed pin can be inserted afterward"
        ),
    )  # type: ignore
    pinCutoutClearance: FloatProperty(
        name=_("Cutout Clearance"),
        default=0.2,
        min=0.0,
        soft_max=2.0,
        description=_(
            "Extra size added to the cutout so the printed pin actually fits into the socket"
        ),
    )  # type: ignore

    mapmode: EnumProperty(
        name=_("mapmode"),
        items=[
            ("FROMPLANE", _("From Selected"), _("Generate the Map from a Flat Plane")),
            (
                "FROMCENTER",
                _("Center + Radius"),
                _("Generate the Map from a Point coordinate and a Radius"),
            ),
            ("2POINTS", _("2 Points"), _("Generate the Map from 2 Coordinates")),
            (
                "GEOJSON",
                _("GeoJSON Boundary"),
                _("Generate the Map clipped to a GeoJSON polygon boundary"),
            ),
        ],
        default="FROMPLANE",
    )  # type: ignore

    geojsonFilePath: StringProperty(
        name=_("GeoJSON File"),
        default="",
        description=_(
            'Path(s) to the imported .geojson boundary file(s), "|"-joined when more than one was selected'
        ),
    )  # type: ignore
    geojsonSimplifyTolerance: FloatProperty(
        name=_("Simplify Tolerance"),
        default=0.1,
        min=0.0,
        soft_max=5.0,
        precision=3,
        description=_(
            "Douglas-Peucker simplification tolerance (map units) applied to the imported boundary. Higher = fewer points but can introduce self-intersections on convoluted borders. Set to 0 to disable simplification."
        ),
    )  # type: ignore
    geojsonPointCount: IntProperty(
        name=_("Boundary Points"),
        default=0,
        description=_(
            "Number of points in the boundary after simplification (read-only, set after import)"
        ),
    )  # type: ignore
    geojsonAreaKm: FloatProperty(
        name=_("Detected Area"),
        default=0.0,
        description=_(
            "Real-world size of the imported boundary in km (read-only, set after import)"
        ),
    )  # type: ignore

    jMapLat: FloatProperty(name="Latitude", default=49.00)  # type: ignore
    jMapLon: FloatProperty(name="Longitude", default=9.00)  # type: ignore
    jMapRadius: FloatProperty(name="Radius im Km", default=200)  # type: ignore

    jMapLat1: FloatProperty(name="Latitude1", default=48.00)  # type: ignore
    jMapLat2: FloatProperty(name="Latitude2", default=49.00)  # type: ignore
    jMapLon1: FloatProperty(name="Longitude1", default=8.00)  # type: ignore
    jMapLon2: FloatProperty(name="Longitude2", default=9.00)  # type: ignore

    specialBlendFile: EnumProperty(
        name="Category",
        description=_("Choose what you want to import"),
        items=get_special_blend_items,
        update=utils.loadCollections,
    )  # type: ignore

    # Custom property to store selection
    specialCollectionName: EnumProperty(
        name="specialCollection",
        description=_("Choose a collection from the external .blend"),
        # items=dynamic_specialCollection_items
        items=lambda self, context: const.specialCollection,
    )  # type: ignore

    # OTHER VARIABLES
    sRunDuration: IntProperty(
        name="runDuration", default=0, description="how long the script was running"
    )  # type: ignore
    sAdditionalExtrusion: FloatProperty(name="sAdditionalExtrusion", default=0)  # type: ignore
    sAutoScale: FloatProperty(name="sAutoScale", default=1)  # type: ignore
    sScaleHor: FloatProperty(
        name="sScaleHor", default=1, description="Scale of the Map"
    )  # type: ignore
    sMapInKm: FloatProperty(
        name="Map Length",
        default=0,
        description="How much Km are the equivalent of the Map Size",
    )  # type: ignore
    sTime_str: StringProperty(name="time_str", default="")  # type: ignore
    modelname: StringProperty(name="modelname", default="")  # type: ignore
    total_length: FloatProperty(name="total_length", default=0)  # type: ignore
    total_elevation: FloatProperty(name="total_elevation", default=0)  # type: ignore
    total_time: FloatProperty(name="total_time", default=0)  # type: ignore
    average_speed: FloatProperty(name="average_speed", default=0)  # type: ignore
    trail_date: StringProperty(name="trail_date", default="")  # type: ignore

    lowestZ: FloatProperty(name="lowestZ", default=0)  # type: ignore
    highestZ: FloatProperty(name="highestZ", default=0)  # type: ignore
    buggyDataset: BoolProperty(name="buggyDataset", default=0)  # type: ignore

    minLat: FloatProperty(name="minLat", default=0)  # type: ignore
    maxLat: FloatProperty(name="maxLat", default=0)  # type: ignore
    minLon: FloatProperty(name="minLon", default=0)  # type: ignore
    maxLon: FloatProperty(name="maxLon", default=0)  # type: ignore

    exportformat: StringProperty(name="exportformat", default="STL")  # type: ignore
    opentopoAdress: StringProperty(
        name="opentopoAdress", default="https://api.opentopodata.org/v1/"
    )  # type: ignore

    currentMap: PointerProperty(name="Map object", type=bpy.types.Object)  # type: ignore
    currentTrail: PointerProperty(name="Trail object", type=bpy.types.Object)  # type: ignore
