#  Copyright (C) 2026  EmGi

# You are free to modify it under the terms of the GNU General Public License as published by the Free Software Foundation.
# You are free to use any models Generated by this Addon Commercially

try:
    from ..premium.utils_pe import textIcon  # type: ignore[import]
except ImportError:

    def textIcon(*_):
        return None


from ..export import *
from .dataclasses import (  # noqa: F401
    GenerationContext,
    GenerationError,
    ValidationError,
)
from .elevation import *
from .generation.elements import (
    _rg_apply_single_color_mode,
    _rg_build_terrain_elements,
)
from .generation.tile_orchestrator import runTileGeneration, generateJustTrail
from .generation.input import (
    _rg_compute_trail_stats,
    _rg_load_coordinates,
    _rg_validate_inputs,
)
from .generation.orchestrator import _GEN_FLAGS, runGeneration
from .generation.output import _rg_assign_materials, _rg_export
from .generation.terrain_gen import _rg_create_map_object
from .geo import *
from .geometry2d import *
from .io_gpx import *
from .mesh_ops import *
from .metadata import *
from .presets import *
from .primitives import *
from .scene import *
from .terrain import *
from .text_objects import *
from .ui_state import *
