#  Copyright (C) 2026  EmGi

# You are free to modify it under the terms of the GNU General Public License as published by the Free Software Foundation.
# You are free to use any models Generated by this Addon Commercially

try:
    from ..premium.utils_pe import textIcon  # type: ignore[import]
except ImportError:
    def textIcon(*_):
        return None

from ..export import *
from .elevation import *
from .generation import *
from .generation import (
    _GEN_FLAGS as _GEN_FLAGS,
)
from .generation import (
    _rg_apply_single_color_mode as _rg_apply_single_color_mode,
)
from .generation import (
    _rg_assign_materials as _rg_assign_materials,
)
from .generation import (
    _rg_build_terrain_elements as _rg_build_terrain_elements,
)
from .generation import (
    _rg_compute_trail_stats as _rg_compute_trail_stats,
)
from .generation import (
    _rg_create_map_object as _rg_create_map_object,
)
from .generation import (
    _rg_export as _rg_export,
)
from .generation import (
    _rg_load_coordinates as _rg_load_coordinates,
)
from .generation import (
    _rg_validate_inputs as _rg_validate_inputs,
)
from .geo import *
from .geometry2d import *
from .io_gpx import *
from .mesh_ops import *
from .metadata import *
from .osm import *
from .presets import *
from .primitives import *
from .scene import *
from .terrain import *
from .text_objects import *
